# pyright: reportUnsupportedDunderAll=false
# ruff: noqa: F401
"""Advanced supported configuration and policy API.

These names are supported for users who need explicit control over specialized
workflow policy. They are intentionally outside the stable ``phospy.api``
aggregate compatibility promise.
"""

from __future__ import annotations

from phospy._api_inventory import ADVANCED_CONFIG_API
from phospy.contracts.configs import (
    PAIRED_DESIGN_POLICY_DUPLICATE_CORRELATION,
    PAIRED_DESIGN_POLICY_FIXED_BLOCK,
    PAIRED_DESIGN_POLICY_REJECT,
    CorrectionMaskPolicy,
    CorrectionMissingnessPolicy,
    DatasetBatchCorrectionConfig,
    DatasetBatchCorrectionMethod,
    DatasetComparisonBuildingConfig,
    DatasetComparisonBuildingPolicy,
    DatasetComparisonPair,
    DatasetGroupCoverageFilterConfig,
    DatasetIntensityTransformConfig,
    DatasetIntensityTransformPolicy,
    DatasetLocalisationMode,
    DatasetMissingDataConfig,
    DatasetMissingDataInputScale,
    DatasetMissingDataKnnNoOverlapPolicy,
    DatasetMissingDataPolicy,
    DatasetNormalisationConfig,
    DatasetNormalisationPolicy,
    DatasetPreprocessingBatchCorrectionConfig,
    DatasetProteinAwarePreparationConfig,
    DatasetProteinAwarePreparationMappingPolicy,
    DatasetProteinAwarePreparationPolicy,
    DatasetRuvReadinessConfig,
    DatasetSiteMatrixConfig,
    DatasetSiteMatrixDuplicateSitePolicy,
    DatasetSiteMatrixMissingDataPolicy,
    DatasetSiteMatrixPolicy,
    DatasetSiteSequenceConflictPolicy,
    DatasetSiteSequenceResolutionConfig,
    DatasetSiteSequenceResolutionMode,
    DatasetTotalProteinCorrectionConfig,
    DatasetTotalProteinCorrectionDuplicatePolicy,
    DatasetTotalProteinCorrectionIdentityConfig,
    DatasetTotalProteinCorrectionIdentityMatchingPolicy,
    DatasetTotalProteinCorrectionIdentityMode,
    DatasetTotalProteinCorrectionPolicy,
    DatasetTotalProteinCorrectionUnmatchedPolicy,
    DifferentialAnalysisConfig,
    DifferentialImputedValuePolicy,
    DifferentialReliabilityProfile,
    EnrichmentIdentifierKind,
    EnrichmentMethod,
    EnrichmentOutsideBackgroundPolicy,
    KinaseActivityConfig,
    KinaseActivityMethod,
    KinaseActivityPValueMethod,
    KinaseActivitySsgseaRankingDirection,
    KinaseAdaptivePolicy,
    KinaseAttritionPolicy,
    KinaseAttritionViolationMode,
    KinasePredictionConfig,
    KinasePredictionMode,
    KinaseProfileMissingValueStrategy,
    KinaseReferenceDisplayAmbiguityPolicy,
    KinaseReliabilityProfile,
    KinaseScoringConfig,
    KinaseScoringMode,
    KinaseSiteSequenceConflictPolicy,
    LocalisationPolicy,
    LocalisationRequirement,
    MultipleTestingConfig,
    MultipleTestingCorrection,
    MultipleTestingMethod,
    ObservationMask,
    OriginallyMissingCellTracking,
    PairedDesignPolicy,
    ProfileSelfInclusionPolicy,
    ReferenceContextCompatibilityPolicy,
    SignalomeAssignmentPolicy,
    SignalomeCandidateScoringPolicy,
    SignalomeClusteringConfig,
    SignalomeConfig,
    SignalomeKinaseNetworkPolicy,
    SignalomeMode,
    SignalomeOutputConfig,
    SignalomePerformanceConfig,
    SignalomeScientificConfig,
    SignalomeScorePreconditioningPolicy,
    SignalomeValidationConfig,
    SpsRuvBatchCorrectionConfig,
    SpsRuvBatchCorrectionMethod,
    TemporaryImputationMethod,
    TemporaryImputationPolicy,
)
from phospy.science.differential.models import EmpiricalBayesConfig

__all__ = ADVANCED_CONFIG_API
