"""Signalome workflow internal constants."""

from __future__ import annotations

SIGNALOME_WORKFLOW_BOUNDARY_MESSAGE_PREFIX = (
    "signalome workflow boundary validation failed"
)

SIGNALOME_EXECUTOR_NETWORK_SEAM = "signalome.executor.network"
SIGNALOME_EXECUTOR_KINASE_SUPPORT_SEAM = "signalome.executor.kinase_support"
SIGNALOME_EXECUTOR_MODULE_CONSTRUCTION_SEAM = "signalome.executor.module_construction"
SIGNALOME_EXECUTOR_EXPANDED_SIGNALOME_SEAM = "signalome.executor.expanded_signalome"

SIGNALOME_INTERPRETER_SITE_ALIGNMENT_SEAM = "signalome.interpreter.site_alignment"
SIGNALOME_INTERPRETER_KINASE_OVERLAP_SEAM = "signalome.interpreter.kinase_overlap"
SIGNALOME_INTERPRETER_PROTEIN_MAPPING_SEAM = "signalome.interpreter.protein_mapping"
SIGNALOME_INTERPRETER_SCORE_PRECONDITIONING_SEAM = (
    "signalome.interpreter.score_preconditioning"
)

SIGNALOME_PROTEIN_RESOLUTION_SOURCE_SITE_METADATA = "dataset.site_metadata.protein_id"
SIGNALOME_PROTEIN_RESOLUTION_SOURCE_SITE_ID_PREFIX = (
    "dataset.phospho.index_protein_prefix"
)

__all__ = [
    "SIGNALOME_EXECUTOR_EXPANDED_SIGNALOME_SEAM",
    "SIGNALOME_EXECUTOR_KINASE_SUPPORT_SEAM",
    "SIGNALOME_EXECUTOR_MODULE_CONSTRUCTION_SEAM",
    "SIGNALOME_EXECUTOR_NETWORK_SEAM",
    "SIGNALOME_INTERPRETER_KINASE_OVERLAP_SEAM",
    "SIGNALOME_INTERPRETER_PROTEIN_MAPPING_SEAM",
    "SIGNALOME_INTERPRETER_SCORE_PRECONDITIONING_SEAM",
    "SIGNALOME_INTERPRETER_SITE_ALIGNMENT_SEAM",
    "SIGNALOME_PROTEIN_RESOLUTION_SOURCE_SITE_ID_PREFIX",
    "SIGNALOME_PROTEIN_RESOLUTION_SOURCE_SITE_METADATA",
    "SIGNALOME_WORKFLOW_BOUNDARY_MESSAGE_PREFIX",
]
