from __future__ import annotations

from typing import Final

from .constants import (
    DEFAULT_PHOSPHO_SENTINEL,
    DEFAULT_TOTAL_SENTINEL,
)

DEFAULT_LOCALIZATION_THRESHOLD: Final[float] = 0.75
DEFAULT_MIN_OBSERVED_VALUES: Final[int] = 4
DEFAULT_MAX_UNMATCHED_FRACTION: Final[float] = 0.0

DEFAULT_KINASE_ACTIVITY_THRESHOLD: Final[float] = 0.6
DEFAULT_KINASE_ACTIVITY_MIN_SUBSTRATES: Final[int] = 3
DEFAULT_KINASE_ACTIVITY_TOP_N_SUBSTRATES: Final[int] = 20

DEFAULT_PREDICTION_ENSEMBLE_SIZE: Final[int] = 10
DEFAULT_PREDICTION_TOP: Final[int] = 50
DEFAULT_PREDICTION_SCORE_THRESHOLD: Final[float] = 0.8
DEFAULT_PREDICTION_INCLUSION: Final[int] = 20
DEFAULT_PREDICTION_N_ITERATIONS: Final[int] = 5
DEFAULT_PREDICTION_DEBUG_TOP_N: Final[int] = 10

DEFAULT_MOTIF_FLANK_SIZE: Final[int] = 7

__all__ = [
    "DEFAULT_KINASE_ACTIVITY_MIN_SUBSTRATES",
    "DEFAULT_KINASE_ACTIVITY_THRESHOLD",
    "DEFAULT_KINASE_ACTIVITY_TOP_N_SUBSTRATES",
    "DEFAULT_LOCALIZATION_THRESHOLD",
    "DEFAULT_MAX_UNMATCHED_FRACTION",
    "DEFAULT_MIN_OBSERVED_VALUES",
    "DEFAULT_MOTIF_FLANK_SIZE",
    "DEFAULT_PHOSPHO_SENTINEL",
    "DEFAULT_PREDICTION_DEBUG_TOP_N",
    "DEFAULT_PREDICTION_ENSEMBLE_SIZE",
    "DEFAULT_PREDICTION_INCLUSION",
    "DEFAULT_PREDICTION_N_ITERATIONS",
    "DEFAULT_PREDICTION_SCORE_THRESHOLD",
    "DEFAULT_PREDICTION_TOP",
    "DEFAULT_TOTAL_SENTINEL",
]
