"""Peptide-level evidence domain exports."""

from phospy.science.evidence.dataset_resolution import (
    DATASET_MULTI_SITE_POLICY_EXCLUDE_FROM_SEQUENCE_SCORING,
    DATASET_MULTI_SITE_POLICY_KEEP_JOINT,
    DATASET_MULTI_SITE_POLICY_REJECT,
    DATASET_MULTI_SITE_POLICY_SPLIT,
    DATASET_PEPTIDE_DUPLICATE_POLICY_RETAIN_ALL_ROWS,
    DATASET_PEPTIDE_MAPPING_WEIGHT_NORMALISATION_UNIT_PER_PEPTIDE,
    DATASET_PEPTIDE_MAPPING_WEIGHT_SOURCE_DERIVED_EQUAL,
    DATASET_PEPTIDE_MAPPING_WEIGHT_SOURCE_EXPLICIT,
    DATASET_PEPTIDE_MIXED_AMBIGUITY_POLICY_SHARED_WEIGHTED_MEAN,
    DATASET_PEPTIDE_TO_SITE_AGGREGATION_POLICY_MAPPING_WEIGHTED_MEAN,
    DATASET_SITE_RESOLUTION_MODE_PEPTIDE_EVIDENCE,
    DATASET_SITE_RESOLUTION_MODE_SITE_LEVEL_RESOLVED,
    SUPPORTED_DATASET_MULTI_SITE_POLICIES,
    SUPPORTED_DATASET_SITE_RESOLUTION_MODES,
    PeptideEvidenceDatasetResolver,
    PeptideEvidenceResolutionResult,
    PeptideEvidenceResolutionSummary,
    build_multi_site_handling_config_for_dataset_policy,
)
from phospy.science.evidence.localisation import (
    LOCALISATION_CONFIDENCE_OUTPUT_COLUMN,
    LOCALISATION_CONFIDENCE_SCALE_PERCENT,
    LOCALISATION_CONFIDENCE_SCALE_PROBABILITY,
    SUPPORTED_LOCALISATION_CONFIDENCE_SCALES,
    LocalisationConfidenceNormalisationReport,
    normalise_localisation_confidence_series,
)
from phospy.science.evidence.models import (
    PeptideEvidenceRecord,
    PeptideEvidenceTable,
    SiteEvidenceMapping,
)
from phospy.science.evidence.modified_peptides import (
    ModifiedPeptideParseResult,
    ModifiedResidue,
    is_phosphorylation_label,
    parse_modified_peptide_sequence,
)
from phospy.science.evidence.multi_site import (
    MULTI_SITE_POLICY_ERROR,
    MULTI_SITE_POLICY_EXCLUDE_FROM_SEQUENCE_SCORING,
    MULTI_SITE_POLICY_FIRST_SITE_COMPATIBILITY,
    MULTI_SITE_POLICY_KEEP_JOINT,
    MULTI_SITE_POLICY_SPLIT_EQUAL_WEIGHT,
    MULTI_SITE_POLICY_SPLIT_WITH_UNCERTAINTY,
    MultiSiteHandlingConfig,
    MultiSiteObservation,
    PhosphoSiteToken,
)

__all__ = [
    "PeptideEvidenceRecord",
    "PeptideEvidenceTable",
    "SiteEvidenceMapping",
    "ModifiedPeptideParseResult",
    "ModifiedResidue",
    "is_phosphorylation_label",
    "parse_modified_peptide_sequence",
    "LOCALISATION_CONFIDENCE_OUTPUT_COLUMN",
    "LOCALISATION_CONFIDENCE_SCALE_PERCENT",
    "LOCALISATION_CONFIDENCE_SCALE_PROBABILITY",
    "SUPPORTED_LOCALISATION_CONFIDENCE_SCALES",
    "LocalisationConfidenceNormalisationReport",
    "normalise_localisation_confidence_series",
    "DATASET_SITE_RESOLUTION_MODE_SITE_LEVEL_RESOLVED",
    "DATASET_SITE_RESOLUTION_MODE_PEPTIDE_EVIDENCE",
    "SUPPORTED_DATASET_SITE_RESOLUTION_MODES",
    "DATASET_MULTI_SITE_POLICY_REJECT",
    "DATASET_MULTI_SITE_POLICY_EXCLUDE_FROM_SEQUENCE_SCORING",
    "DATASET_MULTI_SITE_POLICY_KEEP_JOINT",
    "DATASET_MULTI_SITE_POLICY_SPLIT",
    "DATASET_PEPTIDE_TO_SITE_AGGREGATION_POLICY_MAPPING_WEIGHTED_MEAN",
    "DATASET_PEPTIDE_MAPPING_WEIGHT_SOURCE_EXPLICIT",
    "DATASET_PEPTIDE_MAPPING_WEIGHT_SOURCE_DERIVED_EQUAL",
    "DATASET_PEPTIDE_MAPPING_WEIGHT_NORMALISATION_UNIT_PER_PEPTIDE",
    "DATASET_PEPTIDE_DUPLICATE_POLICY_RETAIN_ALL_ROWS",
    "DATASET_PEPTIDE_MIXED_AMBIGUITY_POLICY_SHARED_WEIGHTED_MEAN",
    "SUPPORTED_DATASET_MULTI_SITE_POLICIES",
    "PeptideEvidenceDatasetResolver",
    "PeptideEvidenceResolutionResult",
    "PeptideEvidenceResolutionSummary",
    "build_multi_site_handling_config_for_dataset_policy",
    "MULTI_SITE_POLICY_ERROR",
    "MULTI_SITE_POLICY_EXCLUDE_FROM_SEQUENCE_SCORING",
    "MULTI_SITE_POLICY_FIRST_SITE_COMPATIBILITY",
    "MULTI_SITE_POLICY_KEEP_JOINT",
    "MULTI_SITE_POLICY_SPLIT_EQUAL_WEIGHT",
    "MULTI_SITE_POLICY_SPLIT_WITH_UNCERTAINTY",
    "MultiSiteHandlingConfig",
    "MultiSiteObservation",
    "PhosphoSiteToken",
]
