"""Science-layer batch-correction numerical executors."""

from phospy.science.batch_correction.executor import (
    SPS_RUV_STYLE_ALGORITHM_DESCRIPTION,
    SPS_RUV_STYLE_BATCH_TERM_ROLE,
    SPS_RUV_STYLE_EXECUTOR_ID,
    SPS_RUV_STYLE_PROTECTED_TERM_ROLE,
    SPS_RUV_STYLE_REPLICATE_METADATA_ROLE,
    DeterministicSpsRuvStyleExecutor,
    SpsRuvStyleExecutor,
    SpsRuvStyleExecutorDiagnostics,
    SpsRuvStyleExecutorResult,
)
from phospy.science.batch_correction.sps_discovery import (
    SPS_DISCOVERY_ALGORITHM_ID,
    SPS_DISCOVERY_ALGORITHM_VERSION,
    SPS_DISCOVERY_CONTROL_SOURCE_TYPE,
    SPS_DISCOVERY_SELECTION_METHOD_CONSENSUS_STABILITY,
    SPS_DISCOVERY_TIE_HANDLING_SITE_KEY_ASCENDING,
    SpsDatasetSiteStatistic,
    SpsDiscoveryConfig,
    SpsDiscoveryProvenance,
    SpsDiscoveryResult,
    SpsDiscoverySelectionMethod,
    SpsDiscoveryTieHandling,
    SpsDiscoveryValidationError,
    SpsDiscoveryValidationIssue,
    SpsDiscoveryValidationResult,
    SpsReferenceDataset,
    SpsReferenceDatasetProvenance,
    SpsSampleConditionAssignment,
    SpsSelectionBoundaryCounts,
    SpsSiteStabilityRecord,
)

__all__ = [
    "SPS_RUV_STYLE_ALGORITHM_DESCRIPTION",
    "SPS_RUV_STYLE_BATCH_TERM_ROLE",
    "SPS_RUV_STYLE_EXECUTOR_ID",
    "SPS_RUV_STYLE_PROTECTED_TERM_ROLE",
    "SPS_RUV_STYLE_REPLICATE_METADATA_ROLE",
    "SPS_DISCOVERY_ALGORITHM_ID",
    "SPS_DISCOVERY_ALGORITHM_VERSION",
    "SPS_DISCOVERY_CONTROL_SOURCE_TYPE",
    "SPS_DISCOVERY_SELECTION_METHOD_CONSENSUS_STABILITY",
    "SPS_DISCOVERY_TIE_HANDLING_SITE_KEY_ASCENDING",
    "DeterministicSpsRuvStyleExecutor",
    "SpsDatasetSiteStatistic",
    "SpsDiscoveryConfig",
    "SpsDiscoveryProvenance",
    "SpsDiscoveryResult",
    "SpsDiscoverySelectionMethod",
    "SpsDiscoveryTieHandling",
    "SpsDiscoveryValidationError",
    "SpsDiscoveryValidationIssue",
    "SpsDiscoveryValidationResult",
    "SpsReferenceDataset",
    "SpsReferenceDatasetProvenance",
    "SpsRuvStyleExecutor",
    "SpsRuvStyleExecutorDiagnostics",
    "SpsRuvStyleExecutorResult",
    "SpsSampleConditionAssignment",
    "SpsSelectionBoundaryCounts",
    "SpsSiteStabilityRecord",
]
