"""Signalome domain constants shared across analysis services."""

from __future__ import annotations

SITE_ID_COLUMN = "site_id"
SITE_KEY_COLUMN = "site_key"
DISPLAY_ID_COLUMN = "display_id"
GENE_SYMBOL_COLUMN = "gene_symbol"
SITE_COLUMN = "site"
KINASE_COLUMN = "kinase"
PROTEIN_GROUP_ID_COLUMN = "protein_group_id"
LEGACY_PROTEIN_GROUP_ID_COLUMN = "protein_id"
PROTEIN_COLUMN = PROTEIN_GROUP_ID_COLUMN
PROTEIN_ACCESSION_COLUMN = "protein_accession"
ISOFORM_ID_COLUMN = "isoform_id"
MODULE_ID_COLUMN = "module_id"
TOP_KINASE_COLUMN = "top_kinase"
TOP_SCORE_COLUMN = "top_score"
TOP_KINASE_CANDIDATES_COLUMN = "top_kinase_candidates"
TOP_KINASE_WEIGHTS_COLUMN = "top_kinase_weights"
TOP_KINASE_TIE_COUNT_COLUMN = "top_kinase_tie_count"
TOP_KINASE_IS_AMBIGUOUS_COLUMN = "top_kinase_is_ambiguous"
TOP_KINASE_SELECTION_POLICY_COLUMN = "top_kinase_selection_policy"
MODULE_TOP_KINASE_COLUMN = "module_top_kinase"
MODULE_TOP_KINASE_CANDIDATES_COLUMN = "module_top_kinase_candidates"
MODULE_TOP_KINASE_TIE_COUNT_COLUMN = "module_top_kinase_tie_count"
MODULE_TOP_KINASE_IS_AMBIGUOUS_COLUMN = "module_top_kinase_is_ambiguous"
MODULE_TOP_KINASE_SELECTION_POLICY_COLUMN = "module_top_kinase_selection_policy"
LEXICOGRAPHIC_TIE_BREAK_POLICY = "max_score_then_lexicographic_tiebreak"
NO_SUPPORT_SELECTION_POLICY = "no_support"
UNSUPPORTED_KINASE = "__UNSUPPORTED__"
DEGREE_COLUMN = "degree"
N_SUBSTRATES_COLUMN = "n_substrates"
SOURCE_KINASE_COLUMN = "source_kinase"
TARGET_KINASE_COLUMN = "target_kinase"
CORRELATION_COLUMN = "correlation"
CORRELATION_REASON_COLUMN = "correlation_reason"
CORRELATION_STATUS_COLUMN = "correlation_status"
SUPPORT_WEIGHT_COLUMN = "support_weight"
VALID_OBSERVATIONS_COLUMN = "valid_observations"

EXPANDED_SIGNALOME_KINASE_COLUMN = "kinase"
EXPANDED_SIGNALOME_LINKED_KINASES_COLUMN = "linked_kinases"
# Stable legacy output field: values are score-supported module IDs, not proof
# that a kinase regulates those modules.
EXPANDED_SIGNALOME_REGULATED_MODULE_IDS_COLUMN = "regulated_module_ids"
EXPANDED_SIGNALOME_SITE_ORDER_COLUMN = "site_order"
EXPANDED_SIGNALOME_SUPPORT_KINASES_COLUMN = "support_kinases"
EXPANDED_SIGNALOME_ROW_KIND_COLUMN = "row_kind"
EXPANDED_SIGNALOME_ROW_KIND_SITE = "site"
EXPANDED_SIGNALOME_ROW_KIND_SUMMARY = "summary"
EXPANDED_SIGNALOME_ASSIGNMENT_POLICY_COLUMN = "assignment_policy"
SITE_CLUSTER_COLUMN = "site_cluster"

JSON_EMPTY_ARRAY = "[]"
MIN_EXPANDED_MODULE_SHARE_PERCENT = 1.0

__all__ = [
    "CORRELATION_COLUMN",
    "CORRELATION_REASON_COLUMN",
    "CORRELATION_STATUS_COLUMN",
    "DEGREE_COLUMN",
    "EXPANDED_SIGNALOME_ASSIGNMENT_POLICY_COLUMN",
    "EXPANDED_SIGNALOME_KINASE_COLUMN",
    "EXPANDED_SIGNALOME_LINKED_KINASES_COLUMN",
    "EXPANDED_SIGNALOME_ROW_KIND_SITE",
    "EXPANDED_SIGNALOME_ROW_KIND_SUMMARY",
    "EXPANDED_SIGNALOME_REGULATED_MODULE_IDS_COLUMN",
    "EXPANDED_SIGNALOME_ROW_KIND_COLUMN",
    "EXPANDED_SIGNALOME_SITE_ORDER_COLUMN",
    "EXPANDED_SIGNALOME_SUPPORT_KINASES_COLUMN",
    "JSON_EMPTY_ARRAY",
    "KINASE_COLUMN",
    "LEGACY_PROTEIN_GROUP_ID_COLUMN",
    "LEXICOGRAPHIC_TIE_BREAK_POLICY",
    "MIN_EXPANDED_MODULE_SHARE_PERCENT",
    "MODULE_ID_COLUMN",
    "MODULE_TOP_KINASE_CANDIDATES_COLUMN",
    "MODULE_TOP_KINASE_COLUMN",
    "MODULE_TOP_KINASE_IS_AMBIGUOUS_COLUMN",
    "MODULE_TOP_KINASE_SELECTION_POLICY_COLUMN",
    "MODULE_TOP_KINASE_TIE_COUNT_COLUMN",
    "NO_SUPPORT_SELECTION_POLICY",
    "N_SUBSTRATES_COLUMN",
    "DISPLAY_ID_COLUMN",
    "GENE_SYMBOL_COLUMN",
    "ISOFORM_ID_COLUMN",
    "PROTEIN_COLUMN",
    "PROTEIN_GROUP_ID_COLUMN",
    "PROTEIN_ACCESSION_COLUMN",
    "SITE_COLUMN",
    "SITE_CLUSTER_COLUMN",
    "SITE_ID_COLUMN",
    "SITE_KEY_COLUMN",
    "SOURCE_KINASE_COLUMN",
    "SUPPORT_WEIGHT_COLUMN",
    "TARGET_KINASE_COLUMN",
    "TOP_KINASE_CANDIDATES_COLUMN",
    "TOP_KINASE_COLUMN",
    "TOP_KINASE_IS_AMBIGUOUS_COLUMN",
    "TOP_KINASE_SELECTION_POLICY_COLUMN",
    "TOP_KINASE_TIE_COUNT_COLUMN",
    "TOP_KINASE_WEIGHTS_COLUMN",
    "TOP_SCORE_COLUMN",
    "UNSUPPORTED_KINASE",
    "VALID_OBSERVATIONS_COLUMN",
]
