from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class Finding:
    line_number: int
    indicator: str
    snippet: str


@dataclass(frozen=True)
class FileFindings:
    path: str
    findings: tuple[Finding, ...]


REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_ROOT = REPO_ROOT / "tests"
DOCS_TESTING_DIR = REPO_ROOT / "docs" / "testing"
REPORT_OUTPUT = DOCS_TESTING_DIR / "orchestration_test_candidates.md"
INVENTORY_CSV = DOCS_TESTING_DIR / "test_inventory.csv"
AUTO_NOTE_PREFIX = "[auto-orchestration]"

INDICATOR_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    ("mock_constructor", re.compile(r"\bMock\s*\(")),
    ("magicmock_constructor", re.compile(r"\bMagicMock\s*\(")),
    ("patch_usage", re.compile(r"\bpatch(?:\.object|\.dict|\.multiple)?\s*\(")),
    ("assert_called_variant", re.compile(r"\bassert_called(?:_once)?(?:_with)?\b")),
    ("assert_not_called", re.compile(r"\bassert_not_called\b")),
    ("call_args_usage", re.compile(r"\bcall_args(?:_list)?\b")),
    ("private_member_access", re.compile(r"\._(?!_)[A-Za-z0-9_]+\b")),
    ("helper_call_order_assertion", re.compile(r"\bassert_has_calls\b|\bmock_calls\b")),
)


def _discover_test_files() -> list[Path]:
    return sorted(
        TESTS_ROOT.rglob("test*.py"), key=lambda file_path: file_path.as_posix()
    )


def _read_lines(path: Path) -> list[str]:
    return path.read_text(encoding="utf-8", errors="replace").splitlines()


def _clean_snippet(line: str) -> str:
    compact = " ".join(line.strip().split())
    compact = compact.replace("|", "\\|")
    return compact[:160]


def _scan_test_file(path: Path) -> FileFindings | None:
    findings: list[Finding] = []
    for line_number, line in enumerate(_read_lines(path), start=1):
        for indicator, pattern in INDICATOR_PATTERNS:
            if pattern.search(line):
                findings.append(
                    Finding(
                        line_number=line_number,
                        indicator=indicator,
                        snippet=_clean_snippet(line),
                    )
                )

    if not findings:
        return None

    relative_path = path.relative_to(REPO_ROOT).as_posix()
    sorted_findings = tuple(
        sorted(findings, key=lambda finding: (finding.line_number, finding.indicator))
    )
    return FileFindings(path=relative_path, findings=sorted_findings)


def _scan_all_tests() -> tuple[int, list[FileFindings]]:
    test_files = _discover_test_files()
    file_findings = [_scan_test_file(path) for path in test_files]
    candidates = [entry for entry in file_findings if entry is not None]
    candidates.sort(key=lambda entry: entry.path)
    return len(test_files), candidates


def _render_report(total_files_scanned: int, candidates: list[FileFindings]) -> str:
    total_findings = sum(len(file_entry.findings) for file_entry in candidates)

    lines: list[str] = []
    lines.append("# Orchestration Test Candidate Report")
    lines.append("")
    lines.append(
        "Generated by `python tools/testing/find_orchestration_test_candidates.py`."
    )
    lines.append("")
    lines.append(
        "> This is a heuristic candidate list for human review. "
        "It does not mean a test is invalid, and not every mock/patch usage is brittle."
    )
    lines.append("")
    lines.append(f"- Total `test*.py` files scanned: {total_files_scanned}")
    lines.append(f"- Candidate files with one or more indicators: {len(candidates)}")
    lines.append(f"- Total indicator hits: {total_findings}")
    lines.append("")
    lines.append("## Indicator Patterns")
    lines.append("")
    for indicator, pattern in INDICATOR_PATTERNS:
        lines.append(f"- `{indicator}`: `{pattern.pattern}`")
    lines.append("")

    if not candidates:
        lines.append("No candidate files were found with the current indicator set.")
        lines.append("")
        return "\n".join(lines)

    lines.append("## Candidates By File")
    lines.append("")
    for file_entry in candidates:
        lines.append(f"### `{file_entry.path}`")
        lines.append("")
        lines.append(f"- Indicator hits: {len(file_entry.findings)}")
        lines.append("")
        lines.append("| Line | Indicator | Snippet |")
        lines.append("| ---: | --- | --- |")
        for finding in file_entry.findings:
            lines.append(
                f"| {finding.line_number} | `{finding.indicator}` | `{finding.snippet}` |"
            )
        lines.append("")

    return "\n".join(lines)


def _rewrite_inventory_notes(candidates: list[FileFindings]) -> None:
    if not INVENTORY_CSV.exists():
        return

    with INVENTORY_CSV.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            return
        if "path" not in reader.fieldnames or "notes" not in reader.fieldnames:
            return
        rows = list(reader)
        fieldnames = list(reader.fieldnames)

    candidate_lookup: dict[str, FileFindings] = {
        entry.path: entry for entry in candidates
    }

    for row in rows:
        path = row.get("path", "")
        existing_notes = row.get("notes", "")
        note_parts = [
            part.strip() for part in existing_notes.split(" | ") if part.strip()
        ]
        note_parts = [
            part for part in note_parts if not part.startswith(AUTO_NOTE_PREFIX)
        ]

        candidate = candidate_lookup.get(path)
        if candidate is not None:
            indicators = sorted({finding.indicator for finding in candidate.findings})
            indicator_list = ", ".join(indicators[:4])
            if len(indicators) > 4:
                indicator_list = f"{indicator_list}, +{len(indicators) - 4} more"
            note_parts.append(
                f"{AUTO_NOTE_PREFIX} {len(candidate.findings)} hit(s); indicators: {indicator_list}"
            )

        row["notes"] = " | ".join(note_parts)

    with INVENTORY_CSV.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def main() -> None:
    total_files_scanned, candidates = _scan_all_tests()
    DOCS_TESTING_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_OUTPUT.write_text(
        _render_report(total_files_scanned, candidates),
        encoding="utf-8",
    )
    _rewrite_inventory_notes(candidates)


if __name__ == "__main__":
    main()
