from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class TestFileInventory:
    path: str
    test_area: str
    line_count: int
    test_function_count: int
    uses_pytest_mark: bool
    uses_parametrization: bool


REPO_ROOT = Path(__file__).resolve().parents[2]
TESTS_ROOT = REPO_ROOT / "tests"
OUTPUT_DIR = REPO_ROOT / "docs" / "testing"
CSV_OUTPUT = OUTPUT_DIR / "test_inventory.csv"
MARKDOWN_OUTPUT = OUTPUT_DIR / "test_inventory.md"

TEST_FUNCTION_PATTERN = re.compile(r"^\s*def\s+test_[A-Za-z0-9_]*\s*\(", re.MULTILINE)
PARAMETRIZATION_PATTERN = re.compile(r"\bparametrize\s*\(")
MANUAL_COLUMNS = (
    "primary_category",
    "recommended_action",
    "protected_risk_or_contract",
    "reviewer",
    "followup_ticket",
    "notes",
)


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _scan_test_file(path: Path) -> TestFileInventory:
    content = _read_text(path)
    relative_path = path.relative_to(REPO_ROOT).as_posix()

    return TestFileInventory(
        path=relative_path,
        test_area=path.parent.name,
        line_count=len(content.splitlines()),
        test_function_count=len(TEST_FUNCTION_PATTERN.findall(content)),
        uses_pytest_mark="pytest.mark" in content,
        uses_parametrization=bool(PARAMETRIZATION_PATTERN.search(content)),
    )


def _discover_test_files() -> list[Path]:
    return sorted(
        TESTS_ROOT.rglob("test*.py"), key=lambda file_path: file_path.as_posix()
    )


def _load_existing_manual_values() -> dict[str, dict[str, str]]:
    if not CSV_OUTPUT.exists():
        return {}

    with CSV_OUTPUT.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            return {}
        if "path" not in reader.fieldnames:
            return {}

        values: dict[str, dict[str, str]] = {}
        for row in reader:
            row_path = row.get("path")
            if not row_path:
                continue
            values[row_path] = {
                column: row.get(column, "") for column in MANUAL_COLUMNS
            }
        return values


def _write_csv(inventory: list[TestFileInventory]) -> None:
    existing_manual_values = _load_existing_manual_values()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with CSV_OUTPUT.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        header = [
            "path",
            "test_area",
            "line_count",
            "test_function_count",
            "uses_pytest_mark",
            "uses_parametrization",
            *MANUAL_COLUMNS,
        ]
        writer.writerow(header)
        for entry in inventory:
            manual_values = existing_manual_values.get(entry.path, {})
            writer.writerow(
                [
                    entry.path,
                    entry.test_area,
                    entry.line_count,
                    entry.test_function_count,
                    str(entry.uses_pytest_mark).lower(),
                    str(entry.uses_parametrization).lower(),
                    *(manual_values.get(column, "") for column in MANUAL_COLUMNS),
                ]
            )


def _render_markdown(inventory: list[TestFileInventory]) -> str:
    total_files = len(inventory)
    total_lines = sum(entry.line_count for entry in inventory)
    total_test_functions = sum(entry.test_function_count for entry in inventory)
    largest_files = sorted(
        inventory, key=lambda entry: (-entry.line_count, entry.path)
    )[:20]

    lines: list[str] = []
    lines.append("# Test Inventory Summary")
    lines.append("")
    lines.append("Generated by `python tools/testing/generate_test_inventory.py`.")
    lines.append("")
    lines.append(f"- Total files: {total_files}")
    lines.append(f"- Total lines: {total_lines}")
    lines.append(f"- Total `test_*` functions: {total_test_functions}")
    lines.append("")
    lines.append("## Manual Classification Workflow")
    lines.append("")
    lines.append(
        "The CSV includes manual review columns for human classification: "
        "`primary_category`, `recommended_action`, `protected_risk_or_contract`, "
        "`reviewer`, `followup_ticket`, and `notes`."
    )
    lines.append(
        "Use the rubric in [test_audit_rubric.md](test_audit_rubric.md) when filling these fields."
    )
    lines.append("")
    lines.append("## Largest 20 files by line count")
    lines.append("")
    lines.append(
        "| Path | Area | Lines | `test_*` defs | Uses `pytest.mark` | Uses parametrization |"
    )
    lines.append("| --- | --- | ---: | ---: | --- | --- |")

    for entry in largest_files:
        lines.append(
            "| "
            f"{entry.path} | "
            f"{entry.test_area} | "
            f"{entry.line_count} | "
            f"{entry.test_function_count} | "
            f"{str(entry.uses_pytest_mark).lower()} | "
            f"{str(entry.uses_parametrization).lower()} |"
        )

    lines.append("")
    return "\n".join(lines)


def _write_markdown(inventory: list[TestFileInventory]) -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    MARKDOWN_OUTPUT.write_text(_render_markdown(inventory), encoding="utf-8")


def main() -> None:
    inventory = [_scan_test_file(path) for path in _discover_test_files()]
    _write_csv(inventory)
    _write_markdown(inventory)


if __name__ == "__main__":
    main()
