"""Public compatibility wrapper for internal contract ownership."""

from phospy.contracts.configs.differential import (
    IMPUTED_VALUE_POLICY_REJECT,
    IMPUTED_VALUE_POLICY_WITHHOLD_IMPUTED_FEATURES,
    MULTIPLE_TESTING_METHOD_BENJAMINI_HOCHBERG,
    PAIRED_DESIGN_POLICY_FIXED_BLOCK,
    PAIRED_DESIGN_POLICY_REJECT,
    SUPPORTED_DIFFERENTIAL_IMPUTED_VALUE_POLICIES,
    SUPPORTED_MULTIPLE_TESTING_METHODS,
    SUPPORTED_PAIRED_DESIGN_POLICIES,
    DifferentialAnalysisConfig,
    DifferentialImputedValuePolicy,
    MultipleTestingConfig,
    PairedDesignPolicy,
)

__all__ = [
    "DifferentialImputedValuePolicy",
    "DifferentialAnalysisConfig",
    "IMPUTED_VALUE_POLICY_REJECT",
    "IMPUTED_VALUE_POLICY_WITHHOLD_IMPUTED_FEATURES",
    "MULTIPLE_TESTING_METHOD_BENJAMINI_HOCHBERG",
    "MultipleTestingConfig",
    "PAIRED_DESIGN_POLICY_FIXED_BLOCK",
    "PAIRED_DESIGN_POLICY_REJECT",
    "PairedDesignPolicy",
    "SUPPORTED_DIFFERENTIAL_IMPUTED_VALUE_POLICIES",
    "SUPPORTED_PAIRED_DESIGN_POLICIES",
    "SUPPORTED_MULTIPLE_TESTING_METHODS",
]
