"""Focused phosphosite identity rule families."""

from phospy.science.sites.identity_rules.contracts import (
    ANALYSIS_READY_DATASET_BASE_IDENTITY_CONTRACT,
    ANALYSIS_READY_DATASET_IDENTITY_CONTRACT,
    ANALYSIS_READY_IDENTITY_COLUMNS,
    BASE_IDENTITY_COLUMNS,
    DISPLAY_CONTEXT_COLUMNS,
    DISPLAY_ID_COLUMN,
    PROTEIN_CONTEXT_COLUMNS,
    REFERENCE_CONTEXT_IDENTITY_FIELDS,
    REFERENCE_CONTEXT_UNKNOWN_CAVEAT_CODE,
    RESULT_IDENTITY_COLUMNS,
    RESULT_TABLE_IDENTITY_CONTRACT,
    SITE_KEY_COLUMN,
    SITE_SEQUENCE_COLUMN,
    WORKFLOW_CENTERED_SEQUENCE_CONTEXT_CONTRACT,
    WORKFLOW_INPUT_IDENTITY_CONTRACT,
    WORKFLOW_PROTEIN_CONTEXT_IDENTITY_CONTRACT,
    WORKFLOW_PROTEIN_SEQUENCE_CONTEXT_IDENTITY_CONTRACT,
    WORKFLOW_SEQUENCE_CONTEXT_IDENTITY_CONTRACT,
    PhosphositeIdentityContract,
    ReferenceContextCompatibilityWarning,
    SequenceContextContract,
    SequenceContextRequirement,
)
from phospy.science.sites.identity_rules.dataset_identity import (
    enforce_analysis_ready_site_key_index,
    enforce_display_id_column,
    enforce_phosphosite_identity_contract,
    enforce_required_identity_text_columns,
    enforce_site_key_column,
    enforce_site_key_column_matches_index,
    enforce_site_key_column_raw_matches_index,
    enforce_site_key_index,
    enforce_site_key_matches_metadata,
    enforce_unique_site_key_identity,
)
from phospy.science.sites.identity_rules.reference_context import (
    validate_reference_context_compatibility,
)
from phospy.science.sites.identity_rules.result_identity import (
    enforce_result_identity_metadata_coherence,
)

__all__ = [
    "ANALYSIS_READY_DATASET_BASE_IDENTITY_CONTRACT",
    "ANALYSIS_READY_DATASET_IDENTITY_CONTRACT",
    "ANALYSIS_READY_IDENTITY_COLUMNS",
    "BASE_IDENTITY_COLUMNS",
    "DISPLAY_CONTEXT_COLUMNS",
    "DISPLAY_ID_COLUMN",
    "PhosphositeIdentityContract",
    "PROTEIN_CONTEXT_COLUMNS",
    "REFERENCE_CONTEXT_IDENTITY_FIELDS",
    "REFERENCE_CONTEXT_UNKNOWN_CAVEAT_CODE",
    "RESULT_IDENTITY_COLUMNS",
    "RESULT_TABLE_IDENTITY_CONTRACT",
    "ReferenceContextCompatibilityWarning",
    "SITE_KEY_COLUMN",
    "SITE_SEQUENCE_COLUMN",
    "SequenceContextContract",
    "SequenceContextRequirement",
    "WORKFLOW_CENTERED_SEQUENCE_CONTEXT_CONTRACT",
    "WORKFLOW_INPUT_IDENTITY_CONTRACT",
    "WORKFLOW_PROTEIN_CONTEXT_IDENTITY_CONTRACT",
    "WORKFLOW_PROTEIN_SEQUENCE_CONTEXT_IDENTITY_CONTRACT",
    "WORKFLOW_SEQUENCE_CONTEXT_IDENTITY_CONTRACT",
    "enforce_analysis_ready_site_key_index",
    "enforce_display_id_column",
    "enforce_phosphosite_identity_contract",
    "enforce_required_identity_text_columns",
    "enforce_result_identity_metadata_coherence",
    "enforce_site_key_column",
    "enforce_site_key_column_matches_index",
    "enforce_site_key_column_raw_matches_index",
    "enforce_site_key_index",
    "enforce_site_key_matches_metadata",
    "enforce_unique_site_key_identity",
    "validate_reference_context_compatibility",
]
