"""Primary user-facing facade for the PhosPy public API.

Import guidance:
- User code should import from top-level `phospy`.
- Public API definitions are authored under `phospy.api`.
- Top-level exports intentionally re-export the supported `phospy.api` surface.
"""

from phospy.api import (
    AnalysisReadyDatasetBuilder,
    AnalysisReadyPhosphoDataset,
    DatasetBuildRequest,
    DatasetComparisonBuildingConfig,
    DatasetMissingDataConfig,
    DatasetPreprocessingConfig,
    DatasetSiteMatrixConfig,
    DatasetTotalProteinCorrectionConfig,
    KinaseActivityConfig,
    KinaseActivityResult,
    KinasePredictionConfig,
    KinasePredictionResult,
    KinaseScoringConfig,
    KinaseScoringResult,
    KinaseWorkflow,
    KinaseWorkflowRequest,
    KinaseWorkflowResult,
    Organism,
    ReferencePreset,
    SignalomeConfig,
    SignalomeWorkflow,
    SignalomeWorkflowRequest,
    SignalomeWorkflowResult,
)
from phospy.errors import (
    DatasetBuildError,
    DatasetValidationError,
    InvalidTransformationStateError,
    PhosPyBuildError,
    PhosPyError,
    PhosPyInputError,
    PhosPyReferenceError,
    PhosPyTransformationError,
    PhosPyValidationError,
    PhosPyWorkflowError,
    ReferenceCompatibilityError,
    ReferenceResolutionError,
    ReferenceValidationError,
    TransformationStateEstablishmentError,
    TransformationValidationError,
    TransformerExecutionError,
    UnsupportedInputFormatError,
    UnsupportedOrganismError,
    WorkflowBoundaryError,
    WorkflowStageError,
    WorkflowValidationError,
)
from phospy.references.models import ReferenceBundle

__all__ = [
    "AnalysisReadyDatasetBuilder",
    "AnalysisReadyPhosphoDataset",
    "DatasetComparisonBuildingConfig",
    "DatasetBuildRequest",
    "DatasetMissingDataConfig",
    "DatasetPreprocessingConfig",
    "DatasetSiteMatrixConfig",
    "DatasetTotalProteinCorrectionConfig",
    "DatasetBuildError",
    "DatasetValidationError",
    "InvalidTransformationStateError",
    "KinaseActivityConfig",
    "KinaseActivityResult",
    "KinasePredictionConfig",
    "KinasePredictionResult",
    "KinaseScoringConfig",
    "KinaseScoringResult",
    "KinaseWorkflowRequest",
    "KinaseWorkflowResult",
    "Organism",
    "PhosPyBuildError",
    "PhosPyError",
    "PhosPyInputError",
    "PhosPyReferenceError",
    "PhosPyTransformationError",
    "PhosPyValidationError",
    "PhosPyWorkflowError",
    "ReferenceCompatibilityError",
    "ReferenceBundle",
    "ReferenceResolutionError",
    "ReferenceValidationError",
    "ReferencePreset",
    "SignalomeConfig",
    "SignalomeWorkflow",
    "SignalomeWorkflowRequest",
    "SignalomeWorkflowResult",
    "TransformationStateEstablishmentError",
    "TransformationValidationError",
    "TransformerExecutionError",
    "UnsupportedInputFormatError",
    "UnsupportedOrganismError",
    "WorkflowBoundaryError",
    "WorkflowStageError",
    "WorkflowValidationError",
    "KinaseWorkflow",
]
