# ruff: noqa: F401
"""Tiered public facade for the supported PhosPy API.

``phospy.api`` is intentionally smaller than the implementation package tree.
It exposes two supported tiers:

Stable public API
    The default user-facing contract: builders, workflow requests, workflow
    classes, primary result objects, reference bundle entrypoints, enums needed
    by examples, and common exception types.

Advanced supported API
    Explicitly supported but narrower contracts for advanced configuration,
    selected result-table inspection, local reference-resource loading, and
    typed policy helpers.

Internal / experimental API
    Validators, workflow interpreters/executors, result assemblers, low-level
    scoring helpers, private provenance serialization, processing-state
    internals, reference manifest validation internals, and compatibility
    constants are not exported here. Import them from their owning modules only
    when working on PhosPy internals.
"""

from phospy.api.builders import AnalysisReadyDatasetBuilder, ReferenceBundleBuilder
from phospy.api.configs import (
    CorrectionMaskPolicy,
    CorrectionMissingnessPolicy,
    DatasetBatchCorrectionConfig,
    DatasetComparisonBuildingConfig,
    DatasetGroupCoverageFilterConfig,
    DatasetIntensityTransformConfig,
    DatasetLocalisationConfig,
    DatasetMissingDataConfig,
    DatasetNormalisationConfig,
    DatasetPreprocessingConfig,
    DatasetProteinAwarePreparationConfig,
    DatasetRuvReadinessConfig,
    DatasetSiteMatrixConfig,
    DatasetSiteSequenceResolutionConfig,
    DatasetTotalProteinCorrectionConfig,
    DatasetTotalProteinCorrectionIdentityConfig,
    DifferentialAnalysisConfig,
    DifferentialImputedValuePolicy,
    EnrichmentConfig,
    EnrichmentIdentifierKind,
    EnrichmentMethod,
    EnrichmentOutsideBackgroundPolicy,
    KinaseActivityConfig,
    KinaseAttritionPolicy,
    KinasePredictionConfig,
    KinaseScoringConfig,
    LocalisationRequirement,
    MultipleTestingConfig,
    MultipleTestingCorrection,
    MultipleTestingMethod,
    ObservationMask,
    OriginallyMissingCellTracking,
    PairedDesignPolicy,
    ProfileSelfInclusionPolicy,
    ReferenceContextCompatibilityPolicy,
    SignalomeClusteringConfig,
    SignalomeConfig,
    SignalomeOutputConfig,
    SignalomePerformanceConfig,
    SignalomeScientificConfig,
    SignalomeValidationConfig,
    SpsRuvBatchCorrectionConfig,
    TemporaryImputationMethod,
    TemporaryImputationPolicy,
)
from phospy.api.datasets import AnalysisReadyPhosphoDataset
from phospy.api.enums import Organism, ReferencePreset
from phospy.api.requests import (
    BatchCovariate,
    CategoricalCovariate,
    ContinuousCovariate,
    Contrast,
    ContrastMatrix,
    DatasetBuildRequest,
    DesignMatrix,
    DifferentialAnalysisRequest,
    EmpiricalBayesConfig,
    EnrichmentIdentifierSetProvenance,
    EnrichmentIdentifierSetSourceType,
    EnrichmentSet,
    EnrichmentSetCollection,
    EnrichmentWorkflowRequest,
    ExperimentalDesign,
    FixedEffectCovariate,
    GeneSetCollection,
    KinaseWorkflowRequest,
    PhosphositeImporter,
    PhosphositeImportRequest,
    PtmSetCollection,
    SampleDesignRecord,
    SignalomeWorkflowRequest,
    all_pairwise_contrasts,
    contrasts_vs_control,
)
from phospy.api.results import (
    DifferentialAnalysisResult,
    EnrichmentResultRecord,
    EnrichmentWorkflowResult,
    KinaseActivityResult,
    KinasePredictionResult,
    KinaseScoringResult,
    KinaseWorkflowResult,
    PhosphositeImportResult,
    ResultCaveat,
    SignalomeWorkflowResult,
)
from phospy.api.workflows import (
    DifferentialAnalysisWorkflow,
    EnrichmentWorkflow,
    KinaseWorkflow,
    SignalomeWorkflow,
)
from phospy.errors import (
    ContractValidationError,
    PhosPyError,
    PhosPyInputError,
    PhosPyReferenceError,
    PhosPyValidationError,
    PhosPyWorkflowError,
    ReferenceCompatibilityError,
    ReferenceResolutionError,
    SignalomeScaleError,
    UnsupportedInputFormatError,
    WorkflowBoundaryError,
    WorkflowValidationError,
)
from phospy.io.bundles.kinase_library import (
    KinaseLibraryResourceLoader,
    load_kinase_library_resource,
)
from phospy.science.datasets.preprocessing.control_sites import (
    ControlSiteAnnotation,
    ControlSiteSet,
    ControlSiteSourceMetadata,
    ControlSiteStatus,
)
from phospy.science.differential.policy_models import TechnicalReplicatePolicy
from phospy.science.references.kinase_library import (
    KinaseLibraryResource,
    KinaseLibraryResourceLoadRequest,
)
from phospy.science.references.models import (
    ReferenceBundle,
    ReferenceBundleBuildRequest,
)
from phospy.science.tables.differential import (
    filter_differential_results,
    rank_differential_results,
)
from phospy.science.transformations.models import IntensityScaleKind

# Stable public API: default imports for user workflows and examples.
_STABLE_PUBLIC_API = (
    "AnalysisReadyDatasetBuilder",
    "AnalysisReadyPhosphoDataset",
    "ReferenceBundleBuilder",
    "DatasetBuildRequest",
    "PhosphositeImporter",
    "PhosphositeImportRequest",
    "PhosphositeImportResult",
    "DatasetLocalisationConfig",
    "DatasetPreprocessingConfig",
    "BatchCovariate",
    "CategoricalCovariate",
    "ContinuousCovariate",
    "FixedEffectCovariate",
    "ExperimentalDesign",
    "SampleDesignRecord",
    "Contrast",
    "DesignMatrix",
    "ContrastMatrix",
    "DifferentialAnalysisRequest",
    "EnrichmentIdentifierSetProvenance",
    "EnrichmentIdentifierSetSourceType",
    "EnrichmentSet",
    "EnrichmentSetCollection",
    "EnrichmentWorkflowRequest",
    "EnrichmentConfig",
    "GeneSetCollection",
    "PtmSetCollection",
    "KinaseWorkflowRequest",
    "SignalomeWorkflowRequest",
    "all_pairwise_contrasts",
    "contrasts_vs_control",
    "DifferentialAnalysisWorkflow",
    "EnrichmentWorkflow",
    "KinaseWorkflow",
    "SignalomeWorkflow",
    "DifferentialAnalysisResult",
    "EnrichmentResultRecord",
    "EnrichmentWorkflowResult",
    "KinaseActivityResult",
    "KinasePredictionResult",
    "KinaseScoringResult",
    "KinaseWorkflowResult",
    "ResultCaveat",
    "SignalomeWorkflowResult",
    "Organism",
    "ReferenceBundle",
    "ReferenceBundleBuildRequest",
    "ReferencePreset",
    "IntensityScaleKind",
    "PhosPyError",
    "PhosPyInputError",
    "UnsupportedInputFormatError",
    "PhosPyValidationError",
    "ContractValidationError",
    "PhosPyReferenceError",
    "ReferenceResolutionError",
    "ReferenceCompatibilityError",
    "PhosPyWorkflowError",
    "WorkflowValidationError",
    "WorkflowBoundaryError",
    "SignalomeScaleError",
)

# Advanced supported API: explicit opt-in configuration and inspection helpers.
_ADVANCED_SUPPORTED_API = (
    "CorrectionMaskPolicy",
    "CorrectionMissingnessPolicy",
    "ObservationMask",
    "OriginallyMissingCellTracking",
    "TemporaryImputationMethod",
    "TemporaryImputationPolicy",
    "ControlSiteAnnotation",
    "ControlSiteSet",
    "ControlSiteSourceMetadata",
    "ControlSiteStatus",
    "DatasetBatchCorrectionConfig",
    "SpsRuvBatchCorrectionConfig",
    "DatasetComparisonBuildingConfig",
    "DatasetGroupCoverageFilterConfig",
    "DatasetIntensityTransformConfig",
    "DatasetMissingDataConfig",
    "DatasetNormalisationConfig",
    "DatasetProteinAwarePreparationConfig",
    "DatasetRuvReadinessConfig",
    "DatasetSiteMatrixConfig",
    "DatasetSiteSequenceResolutionConfig",
    "DatasetTotalProteinCorrectionConfig",
    "DatasetTotalProteinCorrectionIdentityConfig",
    "DifferentialAnalysisConfig",
    "DifferentialImputedValuePolicy",
    "EmpiricalBayesConfig",
    "MultipleTestingConfig",
    "MultipleTestingCorrection",
    "MultipleTestingMethod",
    "PairedDesignPolicy",
    "EnrichmentIdentifierKind",
    "EnrichmentMethod",
    "EnrichmentOutsideBackgroundPolicy",
    "KinaseActivityConfig",
    "KinaseAttritionPolicy",
    "KinasePredictionConfig",
    "KinaseScoringConfig",
    "LocalisationRequirement",
    "ProfileSelfInclusionPolicy",
    "ReferenceContextCompatibilityPolicy",
    "SignalomeConfig",
    "SignalomeScientificConfig",
    "SignalomeClusteringConfig",
    "SignalomeValidationConfig",
    "SignalomeOutputConfig",
    "SignalomePerformanceConfig",
    "TechnicalReplicatePolicy",
    "KinaseLibraryResource",
    "KinaseLibraryResourceLoadRequest",
    "KinaseLibraryResourceLoader",
    "load_kinase_library_resource",
    "filter_differential_results",
    "rank_differential_results",
)

# Internal / experimental API: previous aggregate exports deliberately omitted.
_INTERNAL_EXPERIMENTAL_API = (
    "BatchCorrectionDiagnostics",
    "BatchCorrectionPolicy",
    "BatchCorrectionReport",
    "ComparisonState",
    "DatasetBuildError",
    "DatasetPreprocessingReport",
    "DatasetProcessingState",
    "DatasetValidationError",
    "DATASET_TOTAL_PROTEIN_CORRECTION_UNMATCHED_POLICY_ALLOW_UNCORRECTED",
    "DifferentialContrastDefinition",
    "DifferentialDesignMatrixSummary",
    "DifferentialEmpiricalBayesProvenance",
    "DifferentialFixedEffectCovariateProvenance",
    "DifferentialMissingValuePolicyProvenance",
    "DifferentialPolicyProvenance",
    "DifferentialReplicatePolicyProvenance",
    "DifferentialStatisticalTestingProvenance",
    "DifferentialTechnicalReplicateGroup",
    "DifferentialUnsupportedDesignPolicyProvenance",
    "ENRICHMENT_IDENTIFIER_KIND_DISPLAY_ID",
    "ENRICHMENT_IDENTIFIER_KIND_GENE_SYMBOL",
    "ENRICHMENT_IDENTIFIER_KIND_PHOSPHOSITE",
    "ENRICHMENT_IDENTIFIER_KIND_PROTEIN_ID",
    "ENRICHMENT_IDENTIFIER_KIND_SITE_KEY",
    "ENRICHMENT_METHOD_OVER_REPRESENTATION",
    "GENE_LEVEL_ENRICHMENT_IDENTIFIER_KINDS",
    "IMPUTED_VALUE_POLICY_REJECT",
    "IMPUTED_VALUE_POLICY_WITHHOLD_IMPUTED_FEATURES",
    "IMPORTER_QUALITY_STATUS_NOT_APPLICABLE",
    "IMPORTER_QUALITY_STATUS_NOT_REPORTED",
    "IMPORTER_QUALITY_STATUS_REPORTED",
    "ImporterDetectedIntensityColumn",
    "ImporterDuplicateKeySummary",
    "ImporterFlaggedRowSummary",
    "ImporterLocalisationConfidenceSummary",
    "ImporterMissingIntensitySummary",
    "ImporterQualityCount",
    "ImporterQualityReport",
    "ImporterQualityStatus",
    "ImputationObservationMetadata",
    "IntensityScaleState",
    "InvalidTransformationStateError",
    "KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ALLOW_WITH_DIAGNOSTICS",
    "KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ERROR",
    "KINASE_SCORING_MODE_COMBINED_PROFILE_MOTIF",
    "KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF",
    "KINASE_SCORING_MODE_PHOSR_RANK_WEIGHTED",
    "KINASE_SCORING_MODES",
    "KinaseLibraryMatrix",
    "KinaseLibraryResidueClass",
    "MatrixIntensityScaleState",
    "MissingDataState",
    "MULTIPLE_TESTING_CORRECTION_BENJAMINI_HOCHBERG",
    "MULTIPLE_TESTING_CORRECTION_BENJAMINI_YEKUTIELI",
    "MULTIPLE_TESTING_CORRECTION_BONFERRONI",
    "MULTIPLE_TESTING_CORRECTION_HOLM",
    "MULTIPLE_TESTING_CORRECTION_NONE",
    "MULTIPLE_TESTING_METHOD_BENJAMINI_HOCHBERG",
    "MULTIPLE_TESTING_METHOD_BENJAMINI_YEKUTIELI",
    "MULTIPLE_TESTING_METHOD_BONFERRONI",
    "MULTIPLE_TESTING_METHOD_HOLM",
    "MULTIPLE_TESTING_METHOD_NONE",
    "NormalisationState",
    "PAIRED_DESIGN_POLICY_FIXED_BLOCK",
    "PAIRED_DESIGN_POLICY_REJECT",
    "PhosPyBuildError",
    "PhosPyTransformationError",
    "ProteinAwareMappingDiagnostics",
    "ProteinAwarePreparationReport",
    "ProteinAwarePreparationResult",
    "ProteinAwareSiteEligibility",
    "PTM_LEVEL_ENRICHMENT_IDENTIFIER_KINDS",
    "QuantitativeMeaning",
    "ReferenceBundleMissingValueCount",
    "ReferenceBundleSourceFileValidationReport",
    "ReferenceBundleTableValidationReport",
    "ReferenceBundleValidationReport",
    "ReferenceIdentifierNormalisationValidationError",
    "ReferenceValidationError",
    "RuvReadinessState",
    "SiteMatrixState",
    "SiteSequenceResolutionRowDiagnostic",
    "SiteSequenceResolutionState",
    "SUPPORTED_DIFFERENTIAL_IMPUTED_VALUE_POLICIES",
    "SUPPORTED_ENRICHMENT_IDENTIFIER_KINDS",
    "SUPPORTED_ENRICHMENT_METHODS",
    "SUPPORTED_MULTIPLE_TESTING_CORRECTIONS",
    "SUPPORTED_MULTIPLE_TESTING_METHODS",
    "SUPPORTED_PAIRED_DESIGN_POLICIES",
    "TotalProteinCorrectionDiagnostics",
    "TotalProteinCorrectionDiagnosticsV1",
    "TotalProteinCorrectionState",
    "TransformationStateEstablishmentError",
    "TransformationValidationError",
    "TransformerExecutionError",
    "UnsupportedOrganismError",
    "WorkflowStageError",
)

__all__ = [
    "AnalysisReadyDatasetBuilder",
    "AnalysisReadyPhosphoDataset",
    "ReferenceBundleBuilder",
    "DatasetBuildRequest",
    "PhosphositeImporter",
    "PhosphositeImportRequest",
    "PhosphositeImportResult",
    "DatasetLocalisationConfig",
    "DatasetPreprocessingConfig",
    "BatchCovariate",
    "CategoricalCovariate",
    "ContinuousCovariate",
    "FixedEffectCovariate",
    "ExperimentalDesign",
    "SampleDesignRecord",
    "Contrast",
    "DesignMatrix",
    "ContrastMatrix",
    "DifferentialAnalysisRequest",
    "EnrichmentIdentifierSetProvenance",
    "EnrichmentIdentifierSetSourceType",
    "EnrichmentSet",
    "EnrichmentSetCollection",
    "EnrichmentWorkflowRequest",
    "EnrichmentConfig",
    "GeneSetCollection",
    "PtmSetCollection",
    "KinaseWorkflowRequest",
    "SignalomeWorkflowRequest",
    "all_pairwise_contrasts",
    "contrasts_vs_control",
    "DifferentialAnalysisWorkflow",
    "EnrichmentWorkflow",
    "KinaseWorkflow",
    "SignalomeWorkflow",
    "DifferentialAnalysisResult",
    "EnrichmentResultRecord",
    "EnrichmentWorkflowResult",
    "KinaseActivityResult",
    "KinasePredictionResult",
    "KinaseScoringResult",
    "KinaseWorkflowResult",
    "ResultCaveat",
    "SignalomeWorkflowResult",
    "Organism",
    "ReferenceBundle",
    "ReferenceBundleBuildRequest",
    "ReferencePreset",
    "IntensityScaleKind",
    "PhosPyError",
    "PhosPyInputError",
    "UnsupportedInputFormatError",
    "PhosPyValidationError",
    "ContractValidationError",
    "PhosPyReferenceError",
    "ReferenceResolutionError",
    "ReferenceCompatibilityError",
    "PhosPyWorkflowError",
    "WorkflowValidationError",
    "WorkflowBoundaryError",
    "SignalomeScaleError",
    "CorrectionMaskPolicy",
    "CorrectionMissingnessPolicy",
    "ObservationMask",
    "OriginallyMissingCellTracking",
    "TemporaryImputationMethod",
    "TemporaryImputationPolicy",
    "ControlSiteAnnotation",
    "ControlSiteSet",
    "ControlSiteSourceMetadata",
    "ControlSiteStatus",
    "DatasetBatchCorrectionConfig",
    "SpsRuvBatchCorrectionConfig",
    "DatasetComparisonBuildingConfig",
    "DatasetGroupCoverageFilterConfig",
    "DatasetIntensityTransformConfig",
    "DatasetMissingDataConfig",
    "DatasetNormalisationConfig",
    "DatasetProteinAwarePreparationConfig",
    "DatasetRuvReadinessConfig",
    "DatasetSiteMatrixConfig",
    "DatasetSiteSequenceResolutionConfig",
    "DatasetTotalProteinCorrectionConfig",
    "DatasetTotalProteinCorrectionIdentityConfig",
    "DifferentialAnalysisConfig",
    "DifferentialImputedValuePolicy",
    "EmpiricalBayesConfig",
    "MultipleTestingConfig",
    "MultipleTestingCorrection",
    "MultipleTestingMethod",
    "PairedDesignPolicy",
    "EnrichmentIdentifierKind",
    "EnrichmentMethod",
    "EnrichmentOutsideBackgroundPolicy",
    "KinaseActivityConfig",
    "KinaseAttritionPolicy",
    "KinasePredictionConfig",
    "KinaseScoringConfig",
    "LocalisationRequirement",
    "ProfileSelfInclusionPolicy",
    "ReferenceContextCompatibilityPolicy",
    "SignalomeConfig",
    "SignalomeScientificConfig",
    "SignalomeClusteringConfig",
    "SignalomeValidationConfig",
    "SignalomeOutputConfig",
    "SignalomePerformanceConfig",
    "TechnicalReplicatePolicy",
    "KinaseLibraryResource",
    "KinaseLibraryResourceLoadRequest",
    "KinaseLibraryResourceLoader",
    "load_kinase_library_resource",
    "filter_differential_results",
    "rank_differential_results",
]
