"""Authoritative namespace for the supported PhosPy public contract.

`phospy.api` owns the supported package contract: requests, configs, results,
workflows, dataset/reference entrypoints, and public exception types.
"""

from phospy.api.builders import AnalysisReadyDatasetBuilder
from phospy.api.configs import (
    DatasetComparisonBuildingConfig,
    DatasetIntensityTransformConfig,
    DatasetMissingDataConfig,
    DatasetNormalisationConfig,
    DatasetPreprocessingConfig,
    DatasetSiteMatrixConfig,
    DatasetTotalProteinCorrectionConfig,
    DatasetTotalProteinCorrectionIdentityConfig,
    KinaseActivityConfig,
    KinasePredictionConfig,
    KinaseScoringConfig,
    SignalomeConfig,
)
from phospy.api.datasets import (
    AnalysisReadyPhosphoDataset,
    ComparisonState,
    DatasetPreprocessingReport,
    DatasetProcessingState,
    MissingDataState,
    NormalisationState,
    SiteMatrixState,
    TotalProteinCorrectionDiagnostics,
    TotalProteinCorrectionDiagnosticsV1,
    TotalProteinCorrectionState,
)
from phospy.api.enums import Organism, ReferencePreset
from phospy.api.requests import (
    DatasetBuildRequest,
    KinaseWorkflowRequest,
    SignalomeWorkflowRequest,
)
from phospy.api.results import (
    KinaseActivityResult,
    KinasePredictionResult,
    KinaseScoringResult,
    KinaseWorkflowResult,
    SignalomeWorkflowResult,
)
from phospy.api.workflows import KinaseWorkflow, SignalomeWorkflow
from phospy.errors import (
    DatasetBuildError,
    DatasetValidationError,
    InvalidTransformationStateError,
    PhosPyBuildError,
    PhosPyError,
    PhosPyInputError,
    PhosPyReferenceError,
    PhosPyTransformationError,
    PhosPyValidationError,
    PhosPyWorkflowError,
    ReferenceCompatibilityError,
    ReferenceResolutionError,
    ReferenceValidationError,
    SignalomeScaleError,
    TransformationStateEstablishmentError,
    TransformationValidationError,
    TransformerExecutionError,
    UnsupportedInputFormatError,
    UnsupportedOrganismError,
    WorkflowBoundaryError,
    WorkflowStageError,
    WorkflowValidationError,
)
from phospy.references.models import ReferenceBundle
from phospy.transformations.models import (
    IntensityScaleKind,
    IntensityScaleState,
    MatrixIntensityScaleState,
    QuantitativeMeaning,
)

__all__ = [
    "AnalysisReadyDatasetBuilder",
    "AnalysisReadyPhosphoDataset",
    "ComparisonState",
    "DatasetPreprocessingReport",
    "DatasetProcessingState",
    "MissingDataState",
    "NormalisationState",
    "SiteMatrixState",
    "TotalProteinCorrectionDiagnostics",
    "TotalProteinCorrectionDiagnosticsV1",
    "TotalProteinCorrectionState",
    "DatasetComparisonBuildingConfig",
    "DatasetIntensityTransformConfig",
    "DatasetBuildRequest",
    "DatasetMissingDataConfig",
    "DatasetNormalisationConfig",
    "DatasetPreprocessingConfig",
    "DatasetSiteMatrixConfig",
    "DatasetTotalProteinCorrectionIdentityConfig",
    "DatasetTotalProteinCorrectionConfig",
    "KinaseActivityConfig",
    "KinaseActivityResult",
    "KinasePredictionConfig",
    "KinasePredictionResult",
    "KinaseScoringConfig",
    "KinaseScoringResult",
    "KinaseWorkflowRequest",
    "KinaseWorkflowResult",
    "Organism",
    "IntensityScaleKind",
    "IntensityScaleState",
    "MatrixIntensityScaleState",
    "QuantitativeMeaning",
    "ReferenceBundle",
    "ReferencePreset",
    "SignalomeConfig",
    "SignalomeWorkflow",
    "SignalomeWorkflowRequest",
    "SignalomeWorkflowResult",
    "KinaseWorkflow",
    "DatasetBuildError",
    "DatasetValidationError",
    "InvalidTransformationStateError",
    "PhosPyBuildError",
    "PhosPyError",
    "PhosPyInputError",
    "PhosPyReferenceError",
    "PhosPyTransformationError",
    "PhosPyValidationError",
    "PhosPyWorkflowError",
    "ReferenceCompatibilityError",
    "ReferenceResolutionError",
    "ReferenceValidationError",
    "SignalomeScaleError",
    "TransformationStateEstablishmentError",
    "TransformationValidationError",
    "TransformerExecutionError",
    "UnsupportedInputFormatError",
    "UnsupportedOrganismError",
    "WorkflowBoundaryError",
    "WorkflowStageError",
    "WorkflowValidationError",
]
