from __future__ import annotations

import hashlib
import json
import math
import re
from collections import Counter
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import pytest

from tests.support.duplicate_correlation_parity_scopes import (
    DUPLICATE_CORRELATION_FIXTURE_PARITY_SCOPES,
    DUPLICATE_CORRELATION_PARITY_SCOPE_FIXTURE_IDS,
    ESTIMATOR_AND_GLS_ONLY_FIXTURE_IDS,
    FULL_PIPELINE_FIXTURE_IDS,
    DuplicateCorrelationParityScope,
)

ROOT = Path(__file__).resolve().parents[2]
FIXTURE_ROOT = (
    ROOT
    / "tests"
    / "fixtures"
    / "rewrite_parity"
    / "differential_duplicate_correlation"
)
MANIFEST_PATH = FIXTURE_ROOT / "MANIFEST.json"
GENERATOR_PATH = (
    ROOT
    / "scripts"
    / "active"
    / "generate_differential_duplicate_correlation_limma_fixtures.R"
)

EXPECTED_FIXTURE_IDS = (*FULL_PIPELINE_FIXTURE_IDS, *ESTIMATOR_AND_GLS_ONLY_FIXTURE_IDS)
REQUIRED_FIXTURE_FILES = {
    "matrix.csv",
    "sample_metadata.csv",
    "blocks.csv",
    "design.csv",
    "contrasts.csv",
    "feature_metadata.csv",
    "feature_correlations.csv",
    "duplicate_correlation_summary.csv",
    "fit_coefficients.csv",
    "fit_stdev_unscaled.csv",
    "fit_cov_coefficients.csv",
    "fit_sigma_df.csv",
    "contrast_fit_coefficients.csv",
    "contrast_fit_stdev_unscaled.csv",
    "contrast_fit_cov_coefficients.csv",
    "ebayes_priors.csv",
    "ebayes_statistics.csv",
    "ebayes_global.csv",
}
PUBLIC_STATISTIC_COLUMNS = ("logFC", "t", "P.Value", "adj.P.Val")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")

pytestmark = [pytest.mark.golden, pytest.mark.reproducibility, pytest.mark.release_gate]


def _manifest() -> dict[str, Any]:
    payload = json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    assert isinstance(payload, dict)
    return payload


def _fixture_entry(fixture_id: str) -> dict[str, Any]:
    for entry in _manifest()["fixtures"]:
        if entry["id"] == fixture_id:
            assert isinstance(entry, dict)
            return entry
    raise AssertionError(f"unknown duplicate-correlation fixture {fixture_id!r}")


def _csv(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, keep_default_na=False)


def _numeric(series: pd.Series) -> pd.Series:
    return pd.to_numeric(series.replace("NA", pd.NA), errors="coerce")


def _summary(fixture_id: str) -> dict[str, str]:
    frame = _csv(FIXTURE_ROOT / fixture_id / "duplicate_correlation_summary.csv")
    assert list(frame.columns) == ["field", "value"]
    return dict(zip(frame["field"], frame["value"], strict=True))


def _file_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _assert_residual_variance_matches_sigma(frame: pd.DataFrame) -> None:
    sigma = _numeric(frame["sigma"])
    residual_variance = _numeric(frame["residual_variance"])
    finite = sigma.notna() & residual_variance.notna()
    np.testing.assert_allclose(
        residual_variance.loc[finite].to_numpy(dtype=float),
        sigma.loc[finite].to_numpy(dtype=float) ** 2,
        rtol=1e-12,
        atol=1e-18,
    )
    assert residual_variance.loc[sigma.isna()].isna().all()


def test_duplicate_correlation_limma_manifest_records_pinned_governance() -> None:
    manifest = _manifest()

    assert manifest["manifest_schema_version"] == "fixture-manifest-v1"
    assert manifest["fixture_family"] == "differential_duplicate_correlation_limma"
    assert manifest["classification"] == "external_parity"
    assert manifest["external_implementation"] == {
        "name": "R limma",
        "r_version": "R version 4.5.2 (2025-10-31 ucrt)",
        "bioconductor_version": "3.22",
        "limma_version": "3.66.0",
    }
    assert manifest["pinned_environment"] == {
        "r_version": "R version 4.5.2 (2025-10-31 ucrt)",
        "bioconductor_version": "3.22",
        "limma_version": "3.66.0",
    }
    assert (
        manifest["generator"]
        == "scripts/active/generate_differential_duplicate_correlation_limma_fixtures.R"
    )
    assert manifest["generator_sha256"] == _file_sha256(GENERATOR_PATH)
    assert manifest["seed"] == 20260818
    assert manifest["generation_timestamp_utc"] == "2026-08-18T00:00:00Z"
    assert (
        "Rscript scripts/active/generate_differential_duplicate" in manifest["command"]
    )
    assert manifest["byte_policy"] == "utf-8 LF with final newline"
    assert "NA token for missing numeric values" in manifest["serialization_policy"]
    assert (
        "limma outputs are the external scientific authority"
        in manifest["source_policy"]
    )
    assert "not generated by PhosPy" in manifest["numeric_authority"]
    assert len(manifest["scientific_citation"]) >= 2
    assert "Smyth GK (2004)" in manifest["scientific_citation"][0]
    assert "Ritchie ME" in manifest["scientific_citation"][1]
    assert manifest["redistribution_metadata"]["status"] == (
        "approved_for_repository_test_fixture_redistribution"
    )
    assert (
        "synthetic deterministic inputs"
        in manifest["redistribution_metadata"]["fixture_data_origin"]
    )
    assert (
        "limma source code is not copied"
        in manifest["redistribution_metadata"]["external_package_source_policy"]
    )
    assert (
        manifest["model_policy"]["fixed_effects_design_excludes_block_dummy_variables"]
        is True
    )
    assert manifest["model_policy"]["block_correlation_supplied_to_lmFit"] is True
    assert math.isclose(
        float(
            manifest["model_policy"]["duplicate_correlation_trim_fraction_each_tail"]
        ),
        0.15,
    )
    for digest in manifest["hashes"].values():
        assert SHA256_RE.fullmatch(digest)


def test_duplicate_correlation_limma_manifest_hashes_match_fixture_bytes() -> None:
    manifest = _manifest()

    seen_paths: set[str] = set()
    for item in manifest["files"]:
        relative_path = item["relative_path"]
        assert relative_path not in seen_paths
        seen_paths.add(relative_path)
        assert item["role"] in {"input", "intermediate", "output", "governance"}
        assert SHA256_RE.fullmatch(item["sha256"])
        path = FIXTURE_ROOT / relative_path
        assert path.is_file(), relative_path
        assert _file_sha256(path) == item["sha256"]

    for fixture_id in EXPECTED_FIXTURE_IDS:
        present = {
            Path(item["relative_path"]).name
            for item in manifest["files"]
            if item["fixture"] == fixture_id
        }
        assert present == REQUIRED_FIXTURE_FILES


def test_duplicate_correlation_limma_fixture_parity_scopes_cover_manifest_once() -> (
    None
):
    manifest_fixture_ids = tuple(str(entry["id"]) for entry in _manifest()["fixtures"])
    assert Counter(manifest_fixture_ids) == {
        fixture_id: 1 for fixture_id in manifest_fixture_ids
    }

    committed_fixture_dirs = tuple(
        sorted(path.name for path in FIXTURE_ROOT.iterdir() if path.is_dir())
    )
    assert set(committed_fixture_dirs) == set(manifest_fixture_ids)

    fixture_id_set = set(manifest_fixture_ids)
    assignments = {fixture_id: [] for fixture_id in manifest_fixture_ids}
    unknown_assignments: list[str] = []
    for scope, fixture_ids in DUPLICATE_CORRELATION_PARITY_SCOPE_FIXTURE_IDS.items():
        for fixture_id in fixture_ids:
            if fixture_id not in fixture_id_set:
                unknown_assignments.append(fixture_id)
                continue
            assignments[fixture_id].append(scope)

    unclassified = [
        fixture_id for fixture_id, scopes in assignments.items() if not scopes
    ]
    conflicting = {
        fixture_id: [scope.value for scope in scopes]
        for fixture_id, scopes in assignments.items()
        if len(scopes) != 1
    }
    assert unknown_assignments == []
    assert unclassified == []
    assert conflicting == {}

    assert FULL_PIPELINE_FIXTURE_IDS == (
        "fixture_a_complete_pairs",
        "fixture_b_three_observation_blocks",
        "fixture_c_incomplete_unequal_blocks",
    )
    assert ESTIMATOR_AND_GLS_ONLY_FIXTURE_IDS == ("fixture_d_feature_level_failures",)
    assert (
        DUPLICATE_CORRELATION_FIXTURE_PARITY_SCOPES["fixture_d_feature_level_failures"]
        is DuplicateCorrelationParityScope.ESTIMATOR_AND_GLS_ONLY
    )
    for fixture_id in FULL_PIPELINE_FIXTURE_IDS:
        assert (
            DUPLICATE_CORRELATION_FIXTURE_PARITY_SCOPES[fixture_id]
            is DuplicateCorrelationParityScope.FULL_PIPELINE
        )


@pytest.mark.parametrize("fixture_id", EXPECTED_FIXTURE_IDS)
def test_duplicate_correlation_limma_fixture_schema_and_order(
    fixture_id: str,
) -> None:
    entry = _fixture_entry(fixture_id)
    base = FIXTURE_ROOT / fixture_id
    sample_ids = list(entry["sample_ids"])
    feature_ids = list(entry["feature_ids"])
    design_columns = list(entry["design_columns"])
    contrast_names = list(entry["contrast_names"])

    sample_metadata = _csv(base / "sample_metadata.csv")
    assert list(sample_metadata.columns)[:4] == [
        "sample_order",
        "sample_id",
        "block_id",
        "condition",
    ]
    assert sample_metadata["sample_id"].tolist() == sample_ids
    assert _numeric(sample_metadata["sample_order"]).tolist() == list(
        range(1, len(sample_ids) + 1)
    )

    matrix = _csv(base / "matrix.csv")
    assert list(matrix.columns) == ["feature_id", *sample_ids]
    assert matrix["feature_id"].tolist() == feature_ids

    design = _csv(base / "design.csv")
    assert list(design.columns) == ["sample_id", *design_columns]
    assert design["sample_id"].tolist() == sample_ids
    assert not any("block" in column.lower() for column in design_columns)
    assert np.linalg.matrix_rank(design.loc[:, design_columns].astype(float)) == len(
        design_columns
    )

    contrasts = _csv(base / "contrasts.csv")
    assert list(contrasts.columns) == ["coefficient", *contrast_names]
    assert contrasts["coefficient"].tolist() == design_columns

    feature_metadata = _csv(base / "feature_metadata.csv")
    assert feature_metadata["feature_id"].tolist() == feature_ids
    assert _numeric(feature_metadata["feature_order"]).tolist() == list(
        range(1, len(feature_ids) + 1)
    )

    correlations = _csv(base / "feature_correlations.csv")
    assert list(correlations.columns) == [
        "feature_order",
        "feature_id",
        "atanh_correlation",
        "correlation",
        "status",
        "atanh_correlation_missing_kind",
        "observed_value_count",
        "design_rank",
        "fixture",
    ]
    assert correlations["feature_id"].tolist() == feature_ids
    assert set(correlations["status"]) <= {"estimated", "missing"}
    assert set(correlations["atanh_correlation_missing_kind"]) <= {
        "finite",
        "NA",
        "NaN",
    }
    estimated = correlations["status"] == "estimated"
    assert _numeric(correlations.loc[estimated, "atanh_correlation"]).notna().all()
    assert _numeric(correlations.loc[estimated, "correlation"]).notna().all()
    assert (correlations.loc[~estimated, "atanh_correlation"] == "NA").all()
    assert (correlations.loc[~estimated, "correlation"] == "NA").all()

    assert list(_csv(base / "fit_coefficients.csv").columns) == [
        "feature_id",
        *design_columns,
    ]
    assert list(_csv(base / "fit_stdev_unscaled.csv").columns) == [
        "feature_id",
        *design_columns,
    ]
    assert list(_csv(base / "fit_cov_coefficients.csv").columns) == [
        "coefficient",
        *design_columns,
    ]
    fit_sigma = _csv(base / "fit_sigma_df.csv")
    assert list(fit_sigma.columns) == [
        "feature_id",
        "sigma",
        "residual_variance",
        "residual_degrees_of_freedom",
        "average_expression",
    ]
    assert fit_sigma["feature_id"].tolist() == feature_ids
    _assert_residual_variance_matches_sigma(fit_sigma)

    assert list(_csv(base / "contrast_fit_coefficients.csv").columns) == [
        "feature_id",
        *contrast_names,
    ]
    assert list(_csv(base / "contrast_fit_stdev_unscaled.csv").columns) == [
        "feature_id",
        *contrast_names,
    ]
    assert list(_csv(base / "contrast_fit_cov_coefficients.csv").columns) == [
        "contrast",
        *contrast_names,
    ]

    ebayes = _csv(base / "ebayes_statistics.csv")
    assert list(ebayes.columns) == [
        "feature_id",
        "contrast",
        *PUBLIC_STATISTIC_COLUMNS[:1],
        "AveExpr",
        "SE",
        *PUBLIC_STATISTIC_COLUMNS[1:],
        "B",
        "stdev.unscaled",
        "sigma",
        "residual_degrees_of_freedom",
        "s2.prior",
        "df.prior",
        "s2.post",
        "df.total",
        "var.prior",
        "proportion",
    ]
    assert set(ebayes["contrast"]) == set(contrast_names)
    assert ebayes["feature_id"].tolist() == feature_ids * len(contrast_names)

    priors = _csv(base / "ebayes_priors.csv")
    assert list(priors.columns) == [
        "feature_id",
        "sigma",
        "residual_variance",
        "residual_degrees_of_freedom",
        "s2.prior",
        "df.prior",
        "s2.post",
        "df.total",
        "average_expression",
    ]
    assert priors["feature_id"].tolist() == feature_ids
    _assert_residual_variance_matches_sigma(priors)

    summary = _summary(fixture_id)
    assert summary["fixture"] == fixture_id
    assert int(summary["sample_count"]) == len(sample_ids)
    assert int(summary["feature_count"]) == len(feature_ids)
    assert int(summary["estimated_feature_correlation_count"]) == int(
        entry["estimated_feature_correlation_count"]
    )
    assert int(summary["missing_feature_correlation_count"]) == int(
        entry["missing_feature_correlation_count"]
    )


def test_fixture_a_complete_pairs_cover_nulls_non_nulls_and_no_missing() -> None:
    fixture_id = "fixture_a_complete_pairs"
    base = FIXTURE_ROOT / fixture_id
    matrix = _csv(base / "matrix.csv")
    metadata = _csv(base / "sample_metadata.csv")
    feature_metadata = _csv(base / "feature_metadata.csv")

    assert not (matrix == "NA").any().any()
    assert metadata.groupby("block_id").size().tolist() == [2, 2, 2, 2, 2, 2]
    assert _fixture_entry(fixture_id)["contrast_names"] == ["B_vs_A"]
    assert set(feature_metadata["controlled_case"]) == {"null", "non_null"}


def test_fixture_b_exercises_three_member_block_lower_bound() -> None:
    fixture_id = "fixture_b_three_observation_blocks"
    metadata = _csv(FIXTURE_ROOT / fixture_id / "sample_metadata.csv")
    summary = _summary(fixture_id)

    assert set(metadata.groupby("block_id").size()) == {3}
    assert _fixture_entry(fixture_id)["contrast_names"] == ["T1_vs_T0", "T2_vs_T0"]
    assert float(summary["compound_symmetry_lower_bound"]) == -0.5
    assert -0.5 < float(summary["consensus_correlation"]) < -0.40
    assert -0.5 < float(summary["min_feature_correlation"]) < -0.42


def test_fixture_c_keeps_incomplete_unequal_blocks_usable() -> None:
    fixture_id = "fixture_c_incomplete_unequal_blocks"
    metadata = _csv(FIXTURE_ROOT / fixture_id / "sample_metadata.csv")
    summary = _summary(fixture_id)

    block_sizes = sorted(metadata.groupby("block_id").size().unique().tolist())
    assert block_sizes == [1, 2, 3]
    assert int(summary["singleton_block_count"]) == 2
    assert int(summary["estimated_feature_correlation_count"]) == len(
        _fixture_entry(fixture_id)["feature_ids"]
    )
    assert _fixture_entry(fixture_id)["contrast_names"] == ["B_vs_A", "C_vs_A"]


def test_fixture_d_retains_valid_consensus_with_feature_level_failures() -> None:
    fixture_id = "fixture_d_feature_level_failures"
    base = FIXTURE_ROOT / fixture_id
    correlations = _csv(base / "feature_correlations.csv")
    feature_metadata = _csv(base / "feature_metadata.csv")
    summary = _summary(fixture_id)
    ebayes = _csv(base / "ebayes_statistics.csv")

    assert feature_metadata["controlled_case"].tolist() == [
        "valid_null",
        "valid_non_null",
        "missing_observations_but_estimable",
        "constant_feature",
        "near_constant_feature",
        "feature_specific_rank_loss",
        "insufficient_observed_values",
        "all_observations_missing",
    ]
    assert int(summary["estimated_feature_correlation_count"]) == 4
    assert int(summary["missing_feature_correlation_count"]) == 4
    assert math.isfinite(float(summary["consensus_correlation"]))
    assert set(correlations["atanh_correlation_missing_kind"]) == {
        "finite",
        "NA",
        "NaN",
    }

    valid_rows = ebayes["feature_id"].isin(
        ["D_valid_null", "D_valid_effect", "D_missing_still_estimable"]
    )
    for column in PUBLIC_STATISTIC_COLUMNS:
        assert _numeric(ebayes.loc[valid_rows, column]).notna().all()
    invalid_rows = ebayes["feature_id"].isin(
        ["D_rank_loss_only_A", "D_insufficient_one", "D_all_missing"]
    )
    for column in PUBLIC_STATISTIC_COLUMNS:
        assert (ebayes.loc[invalid_rows, column] == "NA").all()
