"""Compatibility re-exports for kinase table schemas."""

from phospy.science.tables.kinase import (
    KINASE_PROFILE_SCORE_DIAGNOSTIC_COLUMNS,
    KINASE_PROFILE_SCORE_DIAGNOSTIC_REASON_INSUFFICIENT_SUBSTRATES_AFTER_LEAVE_ONE_OUT,
    KINASE_PROFILE_SCORE_DIAGNOSTIC_STATUS_SCORED,
    KINASE_PROFILE_SCORE_DIAGNOSTIC_STATUS_UNSCORED,
    KINASE_SUBSTRATE_CONTRIBUTION_COLUMNS,
    KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_BELOW_MIN_SUBSTRATES,
    KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_MISSING_SCORE_VALUE,
    KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_NO_SCORE_COLUMN,
    KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_NOT_IN_PROFILE_SUPPORT,
    KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_NOT_QUANTIFIED,
    KINASE_SUBSTRATE_CONTRIBUTION_STATUS_EXCLUDED,
    KINASE_SUBSTRATE_CONTRIBUTION_STATUS_INCLUDED,
    KinasePredictionMatrix,
    KinaseProfileScoreDiagnosticTable,
    KinaseScoreMatrix,
    KinaseSubstrateContributionTable,
)

__all__ = [
    "KINASE_PROFILE_SCORE_DIAGNOSTIC_COLUMNS",
    "KINASE_PROFILE_SCORE_DIAGNOSTIC_REASON_INSUFFICIENT_SUBSTRATES_AFTER_LEAVE_ONE_OUT",
    "KINASE_PROFILE_SCORE_DIAGNOSTIC_STATUS_SCORED",
    "KINASE_PROFILE_SCORE_DIAGNOSTIC_STATUS_UNSCORED",
    "KINASE_SUBSTRATE_CONTRIBUTION_COLUMNS",
    "KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_BELOW_MIN_SUBSTRATES",
    "KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_MISSING_SCORE_VALUE",
    "KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_NOT_IN_PROFILE_SUPPORT",
    "KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_NOT_QUANTIFIED",
    "KINASE_SUBSTRATE_CONTRIBUTION_EXCLUDED_NO_SCORE_COLUMN",
    "KINASE_SUBSTRATE_CONTRIBUTION_STATUS_EXCLUDED",
    "KINASE_SUBSTRATE_CONTRIBUTION_STATUS_INCLUDED",
    "KinasePredictionMatrix",
    "KinaseProfileScoreDiagnosticTable",
    "KinaseScoreMatrix",
    "KinaseSubstrateContributionTable",
]
