"""Science-owned differential policy values."""

from __future__ import annotations

from typing import Literal

from phospy.science.statistics.multiple_testing import (
    MULTIPLE_TESTING_CORRECTION_BENJAMINI_HOCHBERG,
    MULTIPLE_TESTING_CORRECTION_BENJAMINI_YEKUTIELI,
    MULTIPLE_TESTING_CORRECTION_BONFERRONI,
    MULTIPLE_TESTING_CORRECTION_HOLM,
    MULTIPLE_TESTING_CORRECTION_NONE,
    SUPPORTED_MULTIPLE_TESTING_CORRECTIONS,
    MultipleTestingCorrection,
)

PairedDesignPolicy = Literal["reject", "fixed_block", "duplicate_correlation"]
DifferentialImputedValuePolicy = Literal["reject", "withhold_imputed_features"]
DifferentialReliabilityProfile = Literal[
    "production",
    "exploratory_single_replicate",
]
MultipleTestingMethod = MultipleTestingCorrection
DIFFERENTIAL_RELIABILITY_PROFILE_PRODUCTION: DifferentialReliabilityProfile = (
    "production"
)
DIFFERENTIAL_RELIABILITY_PROFILE_EXPLORATORY_SINGLE_REPLICATE: DifferentialReliabilityProfile = "exploratory_single_replicate"
SUPPORTED_DIFFERENTIAL_RELIABILITY_PROFILES: tuple[
    DifferentialReliabilityProfile,
    ...,
] = (
    DIFFERENTIAL_RELIABILITY_PROFILE_PRODUCTION,
    DIFFERENTIAL_RELIABILITY_PROFILE_EXPLORATORY_SINGLE_REPLICATE,
)
DIFFERENTIAL_PRODUCTION_MINIMUM_CONDITION_REPLICATES = 2
DIFFERENTIAL_EXPLORATORY_MINIMUM_CONDITION_REPLICATES = 1
MULTIPLE_TESTING_METHOD_NONE: MultipleTestingMethod = MULTIPLE_TESTING_CORRECTION_NONE
MULTIPLE_TESTING_METHOD_BENJAMINI_HOCHBERG: MultipleTestingMethod = (
    MULTIPLE_TESTING_CORRECTION_BENJAMINI_HOCHBERG
)
MULTIPLE_TESTING_METHOD_BONFERRONI: MultipleTestingMethod = (
    MULTIPLE_TESTING_CORRECTION_BONFERRONI
)
MULTIPLE_TESTING_METHOD_HOLM: MultipleTestingMethod = MULTIPLE_TESTING_CORRECTION_HOLM
MULTIPLE_TESTING_METHOD_BENJAMINI_YEKUTIELI: MultipleTestingMethod = (
    MULTIPLE_TESTING_CORRECTION_BENJAMINI_YEKUTIELI
)
SUPPORTED_MULTIPLE_TESTING_METHODS: tuple[MultipleTestingMethod, ...] = tuple(
    SUPPORTED_MULTIPLE_TESTING_CORRECTIONS
)
PAIRED_DESIGN_POLICY_REJECT: PairedDesignPolicy = "reject"
PAIRED_DESIGN_POLICY_FIXED_BLOCK: PairedDesignPolicy = "fixed_block"
PAIRED_DESIGN_POLICY_DUPLICATE_CORRELATION: PairedDesignPolicy = "duplicate_correlation"
IMPUTED_VALUE_POLICY_REJECT: DifferentialImputedValuePolicy = "reject"
IMPUTED_VALUE_POLICY_WITHHOLD_IMPUTED_FEATURES: DifferentialImputedValuePolicy = (
    "withhold_imputed_features"
)
SUPPORTED_PAIRED_DESIGN_POLICIES: tuple[PairedDesignPolicy, ...] = (
    PAIRED_DESIGN_POLICY_REJECT,
    PAIRED_DESIGN_POLICY_FIXED_BLOCK,
    PAIRED_DESIGN_POLICY_DUPLICATE_CORRELATION,
)
SUPPORTED_DIFFERENTIAL_IMPUTED_VALUE_POLICIES: tuple[
    DifferentialImputedValuePolicy,
    ...,
] = (
    IMPUTED_VALUE_POLICY_REJECT,
    IMPUTED_VALUE_POLICY_WITHHOLD_IMPUTED_FEATURES,
)

__all__ = [
    "DIFFERENTIAL_EXPLORATORY_MINIMUM_CONDITION_REPLICATES",
    "DIFFERENTIAL_PRODUCTION_MINIMUM_CONDITION_REPLICATES",
    "DIFFERENTIAL_RELIABILITY_PROFILE_EXPLORATORY_SINGLE_REPLICATE",
    "DIFFERENTIAL_RELIABILITY_PROFILE_PRODUCTION",
    "DifferentialImputedValuePolicy",
    "DifferentialReliabilityProfile",
    "IMPUTED_VALUE_POLICY_REJECT",
    "IMPUTED_VALUE_POLICY_WITHHOLD_IMPUTED_FEATURES",
    "MULTIPLE_TESTING_METHOD_BENJAMINI_HOCHBERG",
    "MULTIPLE_TESTING_METHOD_BENJAMINI_YEKUTIELI",
    "MULTIPLE_TESTING_METHOD_BONFERRONI",
    "MULTIPLE_TESTING_METHOD_HOLM",
    "MULTIPLE_TESTING_METHOD_NONE",
    "MultipleTestingMethod",
    "PAIRED_DESIGN_POLICY_DUPLICATE_CORRELATION",
    "PAIRED_DESIGN_POLICY_FIXED_BLOCK",
    "PAIRED_DESIGN_POLICY_REJECT",
    "PairedDesignPolicy",
    "SUPPORTED_DIFFERENTIAL_IMPUTED_VALUE_POLICIES",
    "SUPPORTED_DIFFERENTIAL_RELIABILITY_PROFILES",
    "SUPPORTED_MULTIPLE_TESTING_METHODS",
    "SUPPORTED_PAIRED_DESIGN_POLICIES",
]
