"""Science-owned enrichment policy values."""

from __future__ import annotations

from typing import Literal

from phospy.science.enrichment.models import (
    ENRICHMENT_IDENTIFIER_KIND_DISPLAY_ID,
    ENRICHMENT_IDENTIFIER_KIND_GENE_SYMBOL,
    ENRICHMENT_IDENTIFIER_KIND_PHOSPHOSITE,
    ENRICHMENT_IDENTIFIER_KIND_PROTEIN_ID,
    ENRICHMENT_IDENTIFIER_KIND_SITE_KEY,
    ENRICHMENT_METHOD_OVER_REPRESENTATION,
    GENE_LEVEL_ENRICHMENT_IDENTIFIER_KINDS,
    MULTIPLE_TESTING_CORRECTION_BENJAMINI_HOCHBERG,
    MULTIPLE_TESTING_CORRECTION_BENJAMINI_YEKUTIELI,
    MULTIPLE_TESTING_CORRECTION_BONFERRONI,
    MULTIPLE_TESTING_CORRECTION_HOLM,
    MULTIPLE_TESTING_CORRECTION_NONE,
    PTM_LEVEL_ENRICHMENT_IDENTIFIER_KINDS,
    SUPPORTED_ENRICHMENT_IDENTIFIER_KINDS,
    SUPPORTED_ENRICHMENT_METHODS,
    SUPPORTED_MULTIPLE_TESTING_CORRECTIONS,
    EnrichmentIdentifierKind,
    EnrichmentMethod,
    MultipleTestingCorrection,
)

ENRICHMENT_OUTSIDE_BACKGROUND_POLICY_ERROR = "error"
ENRICHMENT_OUTSIDE_BACKGROUND_POLICY_DROP = "drop"
EnrichmentOutsideBackgroundPolicy = Literal["error", "drop"]
SUPPORTED_ENRICHMENT_OUTSIDE_BACKGROUND_POLICIES: tuple[
    EnrichmentOutsideBackgroundPolicy,
    ...,
] = (
    ENRICHMENT_OUTSIDE_BACKGROUND_POLICY_ERROR,
    ENRICHMENT_OUTSIDE_BACKGROUND_POLICY_DROP,
)

__all__ = [
    "ENRICHMENT_IDENTIFIER_KIND_DISPLAY_ID",
    "ENRICHMENT_IDENTIFIER_KIND_GENE_SYMBOL",
    "ENRICHMENT_IDENTIFIER_KIND_PHOSPHOSITE",
    "ENRICHMENT_IDENTIFIER_KIND_PROTEIN_ID",
    "ENRICHMENT_IDENTIFIER_KIND_SITE_KEY",
    "ENRICHMENT_METHOD_OVER_REPRESENTATION",
    "ENRICHMENT_OUTSIDE_BACKGROUND_POLICY_DROP",
    "ENRICHMENT_OUTSIDE_BACKGROUND_POLICY_ERROR",
    "EnrichmentIdentifierKind",
    "EnrichmentMethod",
    "EnrichmentOutsideBackgroundPolicy",
    "GENE_LEVEL_ENRICHMENT_IDENTIFIER_KINDS",
    "MULTIPLE_TESTING_CORRECTION_BENJAMINI_HOCHBERG",
    "MULTIPLE_TESTING_CORRECTION_BENJAMINI_YEKUTIELI",
    "MULTIPLE_TESTING_CORRECTION_BONFERRONI",
    "MULTIPLE_TESTING_CORRECTION_HOLM",
    "MULTIPLE_TESTING_CORRECTION_NONE",
    "MultipleTestingCorrection",
    "PTM_LEVEL_ENRICHMENT_IDENTIFIER_KINDS",
    "SUPPORTED_ENRICHMENT_IDENTIFIER_KINDS",
    "SUPPORTED_ENRICHMENT_METHODS",
    "SUPPORTED_ENRICHMENT_OUTSIDE_BACKGROUND_POLICIES",
    "SUPPORTED_MULTIPLE_TESTING_CORRECTIONS",
]
