"""Science-owned kinase workflow policy values."""

from __future__ import annotations

import warnings
from typing import Literal, cast

from phospy.policies import PolicyEnum
from phospy.science.scoring.policy_models import ProfileSelfInclusionPolicy

KINASE_SCORING_MIN_SUBSTRATES_FLOOR = 2
KINASE_SCORING_MODE_PHOSR_RANK_WEIGHTED = "phosr_rank_weighted"
KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF = "kinase_library_motif"
KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF_ONLY = "kinase_library_motif_only"
KINASE_SCORING_MODE_KINASE_LIBRARY_CONTEXTUAL_MOTIF = "kinase_library_contextual_motif"
KINASE_SCORING_MODE_COMBINED_PROFILE_MOTIF = "combined_profile_motif"
KINASE_LIBRARY_MOTIF_ALIAS_DEPRECATION_MESSAGE = (
    "'kinase_library_motif' is deprecated because it requires contextual "
    "profile/reference-substrate eligibility. Use "
    "'kinase_library_contextual_motif' for the current behavior."
)
KinaseScoringMode = Literal[
    "phosr_rank_weighted",
    "kinase_library_contextual_motif",
    "kinase_library_motif",
    "kinase_library_motif_only",
    "combined_profile_motif",
]
KINASE_SCORING_MODE_ALIASES = {
    KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF: (
        KINASE_SCORING_MODE_KINASE_LIBRARY_CONTEXTUAL_MOTIF
    ),
}
KINASE_SCORING_MODES = frozenset(
    {
        KINASE_SCORING_MODE_PHOSR_RANK_WEIGHTED,
        KINASE_SCORING_MODE_KINASE_LIBRARY_CONTEXTUAL_MOTIF,
        KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF,
        KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF_ONLY,
        KINASE_SCORING_MODE_COMBINED_PROFILE_MOTIF,
    }
)
KINASE_SCORING_MODES_REQUIRING_KINASE_LIBRARY = frozenset(
    {
        KINASE_SCORING_MODE_KINASE_LIBRARY_CONTEXTUAL_MOTIF,
        KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF,
        KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF_ONLY,
        KINASE_SCORING_MODE_COMBINED_PROFILE_MOTIF,
    }
)
KINASE_PROFILE_MISSING_VALUE_STRATEGY_STRICT = "strict"
KINASE_PROFILE_MISSING_VALUE_STRATEGY_MEDIAN_SKIPNA = "median_skipna"
KinaseProfileMissingValueStrategy = Literal[
    "strict",
    "median_skipna",
]
KINASE_PROFILE_MISSING_VALUE_STRATEGIES = frozenset(
    {
        KINASE_PROFILE_MISSING_VALUE_STRATEGY_STRICT,
        KINASE_PROFILE_MISSING_VALUE_STRATEGY_MEDIAN_SKIPNA,
    }
)
KINASE_PROFILE_SELF_INCLUSION_POLICY_ALLOW = ProfileSelfInclusionPolicy.ALLOW
KINASE_PROFILE_SELF_INCLUSION_POLICY_LEAVE_ONE_OUT = (
    ProfileSelfInclusionPolicy.LEAVE_ONE_OUT
)
KINASE_PROFILE_SELF_INCLUSION_POLICIES = frozenset(
    {
        KINASE_PROFILE_SELF_INCLUSION_POLICY_ALLOW,
        KINASE_PROFILE_SELF_INCLUSION_POLICY_LEAVE_ONE_OUT,
    }
)
KINASE_ACTIVITY_MIN_SUBSTRATES_FLOOR = 1
KINASE_ACTIVITY_TOP_N_SUBSTRATES_FLOOR = 1
KINASE_ACTIVITY_DEFAULT_THRESHOLD = 0.6
KINASE_ACTIVITY_DEFAULT_MIN_SUBSTRATES = 3
KINASE_ACTIVITY_DEFAULT_TOP_N_SUBSTRATES = 20
KINASE_ACTIVITY_METHOD_SIMPLIFIED_WEIGHTED_SUBSTRATE_ACTIVITY = (
    "simplified_weighted_substrate_activity"
)
KINASE_ACTIVITY_METHOD_KSEA_ZSCORE = "ksea_zscore"
KINASE_ACTIVITY_METHOD_SSGSEA_SUBSTRATE_ENRICHMENT = "ssgsea_substrate_enrichment"
KinaseActivityMethod = Literal[
    "simplified_weighted_substrate_activity",
    "ksea_zscore",
    "ssgsea_substrate_enrichment",
]
KINASE_ACTIVITY_METHODS = frozenset(
    {
        KINASE_ACTIVITY_METHOD_SIMPLIFIED_WEIGHTED_SUBSTRATE_ACTIVITY,
        KINASE_ACTIVITY_METHOD_KSEA_ZSCORE,
        KINASE_ACTIVITY_METHOD_SSGSEA_SUBSTRATE_ENRICHMENT,
    }
)
KINASE_ACTIVITY_KSEA_DEFAULT_MIN_SUBSTRATES = 5
KINASE_ACTIVITY_KSEA_P_VALUE_METHOD_NORMAL_APPROXIMATION = "normal_approximation"
KinaseActivityPValueMethod = Literal["normal_approximation"]
KINASE_ACTIVITY_KSEA_P_VALUE_METHODS = frozenset(
    {KINASE_ACTIVITY_KSEA_P_VALUE_METHOD_NORMAL_APPROXIMATION}
)
KINASE_ACTIVITY_KSEA_DEFAULT_ADJUST_P_VALUES = True
KINASE_ACTIVITY_SSGSEA_DEFAULT_MIN_SUBSTRATES = 5
KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTION_DESCENDING = "descending"
KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTION_ASCENDING = "ascending"
KinaseActivitySsgseaRankingDirection = Literal["descending", "ascending"]
KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTIONS = frozenset(
    {
        KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTION_DESCENDING,
        KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTION_ASCENDING,
    }
)
KINASE_ACTIVITY_SSGSEA_DEFAULT_PERMUTATIONS = 0
KINASE_ACTIVITY_SSGSEA_DEFAULT_RANDOM_SEED = 0
KINASE_ACTIVITY_SSGSEA_DEFAULT_ADJUST_P_VALUES = True
KINASE_ALLOW_MIXED_TOTAL_PROTEIN_QUANTITATIVE_MEANING_DEFAULT = False


class KinaseReliabilityProfile(PolicyEnum):
    EXPLORATORY = "exploratory"
    PRODUCTION = "production"
    CUSTOM = "custom"


KINASE_RELIABILITY_PROFILE_EXPLORATORY = KinaseReliabilityProfile.EXPLORATORY
KINASE_RELIABILITY_PROFILE_PRODUCTION = KinaseReliabilityProfile.PRODUCTION
KINASE_RELIABILITY_PROFILE_CUSTOM = KinaseReliabilityProfile.CUSTOM
KINASE_RELIABILITY_PROFILES = frozenset(
    {
        KINASE_RELIABILITY_PROFILE_EXPLORATORY,
        KINASE_RELIABILITY_PROFILE_PRODUCTION,
        KINASE_RELIABILITY_PROFILE_CUSTOM,
    }
)


class KinaseSiteSequenceConflictPolicy(PolicyEnum):
    ERROR = "error"
    PREFER_REFERENCE = "prefer_reference"
    PREFER_DATASET = "prefer_dataset"


KINASE_SITE_SEQUENCE_CONFLICT_POLICY_ERROR = KinaseSiteSequenceConflictPolicy.ERROR
KINASE_SITE_SEQUENCE_CONFLICT_POLICY_PREFER_REFERENCE = (
    KinaseSiteSequenceConflictPolicy.PREFER_REFERENCE
)
KINASE_SITE_SEQUENCE_CONFLICT_POLICY_PREFER_DATASET = (
    KinaseSiteSequenceConflictPolicy.PREFER_DATASET
)
KINASE_SITE_SEQUENCE_CONFLICT_POLICIES = frozenset(
    {
        KINASE_SITE_SEQUENCE_CONFLICT_POLICY_ERROR,
        KINASE_SITE_SEQUENCE_CONFLICT_POLICY_PREFER_REFERENCE,
        KINASE_SITE_SEQUENCE_CONFLICT_POLICY_PREFER_DATASET,
    }
)
KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ERROR = "error"
KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ALLOW_WITH_DIAGNOSTICS = (
    "allow_with_diagnostics"
)
KinaseReferenceDisplayAmbiguityPolicy = Literal[
    "error",
    "allow_with_diagnostics",
]
KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICIES = frozenset(
    {
        KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ERROR,
        KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ALLOW_WITH_DIAGNOSTICS,
    }
)
KINASE_ATTRITION_POLICY_ON_VIOLATION_ERROR = "error"
KINASE_ATTRITION_POLICY_ON_VIOLATION_WARN = "warn"
KinaseAttritionViolationMode = Literal["error", "warn"]
KINASE_ATTRITION_POLICY_ON_VIOLATION_MODES = frozenset(
    {
        KINASE_ATTRITION_POLICY_ON_VIOLATION_ERROR,
        KINASE_ATTRITION_POLICY_ON_VIOLATION_WARN,
    }
)


def normalize_kinase_scoring_mode(
    value: object,
    *,
    warn_on_deprecated_alias: bool = False,
) -> KinaseScoringMode:
    """Return the canonical internal scoring-mode name for public aliases."""

    text = str(value)
    normalized = KINASE_SCORING_MODE_ALIASES.get(text, text)
    if text in KINASE_SCORING_MODE_ALIASES and warn_on_deprecated_alias:
        warnings.warn(
            KINASE_LIBRARY_MOTIF_ALIAS_DEPRECATION_MESSAGE,
            DeprecationWarning,
            stacklevel=3,
        )
    return cast(KinaseScoringMode, normalized)


__all__ = [
    "KINASE_ACTIVITY_DEFAULT_MIN_SUBSTRATES",
    "KINASE_ACTIVITY_DEFAULT_THRESHOLD",
    "KINASE_ACTIVITY_DEFAULT_TOP_N_SUBSTRATES",
    "KINASE_ACTIVITY_KSEA_DEFAULT_ADJUST_P_VALUES",
    "KINASE_ACTIVITY_KSEA_DEFAULT_MIN_SUBSTRATES",
    "KINASE_ACTIVITY_KSEA_P_VALUE_METHOD_NORMAL_APPROXIMATION",
    "KINASE_ACTIVITY_KSEA_P_VALUE_METHODS",
    "KINASE_ACTIVITY_METHODS",
    "KINASE_ACTIVITY_METHOD_KSEA_ZSCORE",
    "KINASE_ACTIVITY_METHOD_SIMPLIFIED_WEIGHTED_SUBSTRATE_ACTIVITY",
    "KINASE_ACTIVITY_METHOD_SSGSEA_SUBSTRATE_ENRICHMENT",
    "KINASE_ACTIVITY_MIN_SUBSTRATES_FLOOR",
    "KINASE_ACTIVITY_SSGSEA_DEFAULT_ADJUST_P_VALUES",
    "KINASE_ACTIVITY_SSGSEA_DEFAULT_MIN_SUBSTRATES",
    "KINASE_ACTIVITY_SSGSEA_DEFAULT_PERMUTATIONS",
    "KINASE_ACTIVITY_SSGSEA_DEFAULT_RANDOM_SEED",
    "KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTION_ASCENDING",
    "KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTION_DESCENDING",
    "KINASE_ACTIVITY_SSGSEA_RANKING_DIRECTIONS",
    "KINASE_ACTIVITY_TOP_N_SUBSTRATES_FLOOR",
    "KINASE_ALLOW_MIXED_TOTAL_PROTEIN_QUANTITATIVE_MEANING_DEFAULT",
    "KINASE_ATTRITION_POLICY_ON_VIOLATION_ERROR",
    "KINASE_ATTRITION_POLICY_ON_VIOLATION_MODES",
    "KINASE_ATTRITION_POLICY_ON_VIOLATION_WARN",
    "KINASE_LIBRARY_MOTIF_ALIAS_DEPRECATION_MESSAGE",
    "KINASE_PROFILE_MISSING_VALUE_STRATEGIES",
    "KINASE_PROFILE_MISSING_VALUE_STRATEGY_MEDIAN_SKIPNA",
    "KINASE_PROFILE_MISSING_VALUE_STRATEGY_STRICT",
    "KINASE_PROFILE_SELF_INCLUSION_POLICIES",
    "KINASE_PROFILE_SELF_INCLUSION_POLICY_ALLOW",
    "KINASE_PROFILE_SELF_INCLUSION_POLICY_LEAVE_ONE_OUT",
    "KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICIES",
    "KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ALLOW_WITH_DIAGNOSTICS",
    "KINASE_REFERENCE_DISPLAY_AMBIGUITY_POLICY_ERROR",
    "KINASE_RELIABILITY_PROFILE_CUSTOM",
    "KINASE_RELIABILITY_PROFILE_EXPLORATORY",
    "KINASE_RELIABILITY_PROFILE_PRODUCTION",
    "KINASE_RELIABILITY_PROFILES",
    "KINASE_SCORING_MIN_SUBSTRATES_FLOOR",
    "KINASE_SCORING_MODE_ALIASES",
    "KINASE_SCORING_MODE_COMBINED_PROFILE_MOTIF",
    "KINASE_SCORING_MODE_KINASE_LIBRARY_CONTEXTUAL_MOTIF",
    "KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF",
    "KINASE_SCORING_MODE_KINASE_LIBRARY_MOTIF_ONLY",
    "KINASE_SCORING_MODE_PHOSR_RANK_WEIGHTED",
    "KINASE_SCORING_MODES",
    "KINASE_SCORING_MODES_REQUIRING_KINASE_LIBRARY",
    "KINASE_SITE_SEQUENCE_CONFLICT_POLICIES",
    "KINASE_SITE_SEQUENCE_CONFLICT_POLICY_ERROR",
    "KINASE_SITE_SEQUENCE_CONFLICT_POLICY_PREFER_DATASET",
    "KINASE_SITE_SEQUENCE_CONFLICT_POLICY_PREFER_REFERENCE",
    "KinaseActivityMethod",
    "KinaseActivityPValueMethod",
    "KinaseActivitySsgseaRankingDirection",
    "KinaseAttritionViolationMode",
    "KinaseProfileMissingValueStrategy",
    "KinaseReferenceDisplayAmbiguityPolicy",
    "KinaseReliabilityProfile",
    "KinaseScoringMode",
    "KinaseSiteSequenceConflictPolicy",
    "ProfileSelfInclusionPolicy",
    "normalize_kinase_scoring_mode",
]
